### ISSUE TITLE
Server Requirements: MySQL Permissions: include LOCK TABLES

### ISSUE THREAD

**Issue by BridgingUnit** [craftcms/docs#103]
Running updater from 3.0.0-RC16 to 3.0.1 within CP I hit an issue with the 'Couldn't back up database, how would you like to proceed?' error screen.

Looking in log file for mysqldump showed up error suggesting the mysql user didn't have LOCK TABLES permissions. 

After adding them for the user, the updater worked.

Docs should probably reflect this. Or have I got some other issue...?

**Comment by brandonkelly** [comment]
Thanks for pointing that out!
