### ISSUE TITLE
Improve “Email Fields”

### ISSUE THREAD

**Issue by OwenMelbz** [craftcms/docs#103]
I have a suggestion for https://craftcms.com/docs/3.x/email-fields.html:

When creating a custom email template for default emails such as Password Reset, or Activate account - There's no documentation to say what variables you have access to within these templates, or what the block should be called etc.

**Comment by mattstein** [comment]
This page is obviously underwhelming @OwenMelbz, but it sounds like you’re describing the process of customizing Craft’s email templates and not the “Email” field type—right?

**Comment by OwenMelbz** [comment]
Yes..

I guess the title of the page and url is misleading as it doesn't mention that it is the "Email Field Type" - "Email Fields" could also suggest the fields you get within emails :D

**Comment by mattstein** [comment]
Understood! Documenting system emails is on my list, but I’ll leave this issue open until the _Email Fields_ page has some actual words on it.

**Comment by mattstein** [comment]
Added in 00962b50dfbe913908722bbbe96545411fa47093. Will cover customizing system emails later.
