### ISSUE TITLE
FR: Some design love (plus a small mobile issue)

### ISSUE THREAD

**Issue by bensomething** [craftcms/docs#104]
I can only imagine how busy the team's been leading up to the release of 3, and I have no doubt you've already got plans to spend some more time on the docs, but I got bored and wanted to see how they'd look if they adopted the control panel's visual styling. I threw something together super quickly and thought I'd share: https://craftdocs.netlify.com

While some of the **Plugin Development** pages have TOCs, it'd be great to have them on every page for a quick overview of what's included.

Oh, and the new search bar (which works a treat) is looking a little wonky on mobile.

**Comment by brandonkelly** [comment]
Thanks for taking the time to do that!

We do plan on improving the styling and functionality of the docs; we’ll keep this in mind :)

cc @benjamindavid @samhernandez
