### ISSUE TITLE
Plugin Store: Page Not Found

### ISSUE THREAD

**Issue by wooge** [craftcms/docs#110]
There is a possible bug with the store. To produce it, go to the file:

> /config/general.php

And the setting:

> omitScriptNameInUrls' => false,

If it is set to "false", the Plugin Store fails to load. Switching it to **true** fixes this.

**Comment by brandonkelly** [comment]
Thanks for reporting! We'll get this fixed.

FFR, please post Craft issues at https://github.com/craftcms/cms/issues :)

**Comment by wooge** [comment]
Crud — apologies, don't know how I ended up in the /docs section. My bad.  Will do!

**Comment by benjamindavid** [comment]
@wooge it probably happens because you are only reloading the page after changing the `omitScriptNameInUrls` config. Try to click on the Plugin Store link instead of reloading the page so that the new config can properly be taken into account.

**Comment by wooge** [comment]
@benjamindavid — I just logged into my install, set omitScriptNameInUrls to false, clicked on the plugin store, and got a Page Not Found error again. But a clean install of craft 3.0.3 doesn't exhibit the same issue. Must be something wrong with my particular install. Wish there was a want to re-download all of core without wiping the site.

**Comment by brandonkelly** [comment]
> Wish there was a want to re-download all of core without wiping the site.

Nuke your `vendor/` folder and run `composer install` :)

**Comment by wooge** [comment]
Done. Problem still persists (on only this install of Craft), so no worries — I'll  just leave the config setting to true and it all works. Thank you!!
