### ISSUE TITLE
Register Element Sources Event Tweak

### ISSUE THREAD

**Issue by magnessjo** [craftcms/docs#112]
In the [example](https://github.com/craftcms/docs/blob/v3/en/updating-plugins.md#modifyentrysources-modifycategorysources-modifyassetsources--modifyusersources)

The new syntax appears to be wrong (or I was/am very confused).  It took me a while to get it to work correctly so I wanted to make sure the documents are correct so others aren't confused as well.  

For me, I had to merge in an array for the heading and each individual source. The $sources[] should be $event->sources[].  

Example of iterating over the categories (rather than statuses).  

```php
    Event::on(Entry::class, Element::EVENT_REGISTER_SOURCES, function(RegisterElementSourcesEvent $event) {

      if ($event->context === 'index') {

        // Set Heading

        $event->sources[] = [ 'heading' => \Craft::t('app', 'Filter By Categories') ];

        // Set Each Category

        $categories = Category::find()->all();

        foreach ($categories as &$category) {
          $event->sources[] = [
            'key' => 'category:'.$category->id,
            'label' => $category->title,
            'criteria' => ['relatedTo' => [ 'targetElement' => $category->id]]
          ];
        }

      }

    });
```

**Comment by brandonkelly** [comment]
Yep you’re right, thanks for pointing that out! And sorry for the confusion.
