### ISSUE TITLE
Search doesn’t find some content from “Changes in Craft 3” article

### ISSUE THREAD

**Issue by carlcs** [craftcms/docs#114]
> No results found for query “getSegment”

The methods listed in this table can’t be found via the search.
https://docs.craftcms.com/v3/changes-in-craft-3.html#template-functions

**Comment by brandonkelly** [comment]
@samhernandez any chance we can combine the Algolia search results for Craft 3 Documentation + Craft 3 Class Reference? (And ditto for Craft 2 Documentation + Craft 2 Class Reference?)

**Comment by brandonkelly** [comment]
Just talked this over internally and decided against combining the search results across documentation “zones”, as in general it will probably add more noise than it’s worth.

Instead we’ll start going through the docs and create links to the class reference where appropriate, like in that Template Functions section.

**Comment by carlcs** [comment]
I’m revisiting this issue because I’m not sure if you misunderstood what it was about, or if it’s rather my lack of understanding of how you’re pushing data to Algolia. From what I can see “getSegment” is included in this Markdown file https://github.com/craftcms/docs/blob/v3/docs/changes-in-craft-3.md

**Comment by brandonkelly** [comment]
Ahh sorry, I misenderstood the issue. @samhernandez maybe worth asking Algolia about that?

**Comment by samhernandez** [comment]
Looks like our [DocSearch config](https://github.com/algolia/docsearch-configs/blob/master/configs/craftcms.json#L42) only indexes text in headings, `<p>`, and `<li>` tags. Makes sense to not dilute indexed search words with table data, except in this case. I'll submit a PR

**Comment by samhernandez** [comment]
Here's that PR: https://github.com/algolia/docsearch-configs/pull/484
