### ISSUE TITLE
Update some documents with new Craft 3 licence

### ISSUE THREAD

**Issue by dreamseeker** [craftcms/docs#115]
Craft Client is not available, so remove Client’s Account section in users.md.

- https://github.com/craftcms/docs/blob/v3/en/users.md

Following documents has `Craft Personal` or `Craft Client or Craft Pro` strings.

- https://github.com/craftcms/docs/blob/v3/en/sections-and-entries.md
- https://github.com/craftcms/docs/blob/v3/en/users.md

**Comment by brandonkelly** [comment]
Whoops, looks like we updated the v2 docs (8eca40b3b900ac7f20af6e128b5e615f44305666) but forgot to update the v3 docs. Thanks for the reminder!
