### ISSUE TITLE
Improvements to Element Type project config example

### ISSUE THREAD

**Issue by dmatthams** [craftcms/docs#116]
I found it very hard to get my head around the [project config example for custom element types](https://craftcms.com/docs/3.x/extend/element-types.html#custom-fields). I'm new to plugin development so this could very well be the problem – so take this or leave it 😉

For context, I have a custom element type with a single field layout. The field layout is on the settings page so I have a custom controller that saves both the settings and the field layout at the same time. I only needed to save the field layout into project config.

**Just a quick list of issues:**

- The first issue I found was that I didn't have a service setup for my component as I didn't need it, the example assumes that you might have. So I struggled to see where the save/update/delete methods would live.
- I thought maybe the example would link in with that of the [Supporting project config](https://craftcms.com/docs/3.x/extend/project-config.html#is-project-config-support-right-for-you) page, but it doesn't seem to.
- It's not clear where the variable `$data` comes from, I understand now that it's `$event->newValue;`

### What would have made it easier to understand
If the example just focused on a service that handles _just_ the field layout, rather than being part of a component's service then it would be a whole lot clearer. Either that or it was a continuation of the `ProductType` example on the [Supporting project config](https://craftcms.com/docs/3.x/extend/project-config.html#is-project-config-support-right-for-you) page.

### What I ended up with (Maybe it's helpful?)
I made a `FieldLayout` service with a `saveFieldLayout($fieldLayout)` method  (which receives a field layout from a controller) and a `handleUpdateFieldLayout(ConfigEvent $event)` method to handle the updates.

In any case the docs have still been great and I'm doing things that I never thought I'd be able to do. 👍

**Comment by dmatthams** [comment]
Looking more into this I think that I should have a service specifically for my element type, and not have this logic in a controller for field layouts – so ignore that bit.

**Comment by AugustMiller** [comment]
I've made some significant changes to both the _Element Types_ and _Project Config_ pages that clarify some aspects of this, so I'm closing for now. I would still like to generate some more practical examples of Project Config that we could point to as a primer—diving in with elements + field layouts is definitely a tall order!
