### ISSUE TITLE
Image Transforms: webp is missing in the list of image formats

### ISSUE THREAD

**Issue by craftedsystems** [craftcms/docs#121]
### Description

The option to use **webp** as image format in image transforms is missing in the docs.

* [Defining Transforms from the Control Panel](https://craftcms.com/docs/3.x/image-transforms.html#defining-transforms-from-the-control-panel)
* [Possible Values](https://craftcms.com/docs/3.x/image-transforms.html#defining-transforms-in-your-templates)

### Additional info

- Craft version: 3

**Comment by mattstein** [comment]
Thanks for pointing this out @craftedsystems!
