### ISSUE TITLE
[FR] Make it easier to find user permissions list

### ISSUE THREAD

**Issue by mmikkel** [craftcms/docs#122]
### Description

[The complete list of available user permissions](https://craftcms.com/docs/3.x/user-management.html#permissions) is super neat and an invaluable resource when working with permissions, but it's buried in the User Management page and is impossible to find via search.

It'd be great if searching for "permissions" or the like would actually yield a result for that list/page, or if the permissions list had a dedicated page in the docs to make it easier to find.

**Comment by mattstein** [comment]
We have a trick for that! Just updated in b9c250bdeba638621ee30840e1380c0fa5651619—it’s not perfect a search for `permissions` should always give a boost to the [User Management page](https://craftcms.com/docs/3.x/user-management.html) and land it in a top spot.

Thanks for pointing this out.

**Comment by mmikkel** [comment]
Excellent, this helps a lot! Thanks :)
