### ISSUE TITLE
Explain/link to Aliases on the Assets page

### ISSUE THREAD

**Issue by j-greig** [craftcms/docs#122]
It might be helpful to mention `@web` and `@webroot` on the https://docs.craftcms.com/v3/assets.html page as this is often asked about in Slack.

![example asset config](https://user-images.githubusercontent.com/616194/40298287-8c9e165c-5cda-11e8-820b-6083c5cc171b.png)

**Comment by brandonkelly** [comment]
Looks like this is done now.
