### ISSUE TITLE
Getting "selected" status of radio/checkboxes fields doesn't work

### ISSUE THREAD

**Issue by skoften** [craftcms/docs#123]
Not sure if template/tag related issues should be posted here, but it seems that grabbing the "selected" status of multiple check/radioboxes doesn't work.

According to the docs:

```
In either case, you can output an option’s label by typing {{ option.label }} instead, and you can tell if the option is selected or not via option.selected.
```

But this doesn't work;

```
{% set email_preferences = craft.app.fields.getFieldByHandle('email_preferences') %}
										
{% for option in email_preferences.options %}
										
	{% option.label }} is {{ option.selected }}<br />
    
{% endfor %}
```

It's a custom field with type checkbox and multiple rows.

![screen shot 2018-05-22 at 17 17 22](https://user-images.githubusercontent.com/1286410/40372003-169191cc-5de4-11e8-939b-7b3663454105.jpg)

Any help is appreciated.

**Comment by brandonkelly** [comment]
`selected` will only be set in the context of an actual entry value, whereas you are looping through the options on the field’s settings. (Notice how all the examples on https://docs.craftcms.com/v3/checkboxes-fields.html access the field’s value via `entry.checkboxFieldHandle`.)

Does that help clarify?

**Comment by skoften** [comment]
Hi Brandon,

I am still a little bit confused, sorry. 

I am trying to create multiple checkboxes for users, which they can update in their profile. In this case so they can apply to different email subscriptions. 

So I created a field, type checkbox, added multiple rows. But I can't find any way to read and update them on the **front end**. The weird part is, the same checkboxes work fine from within the control panel profile page, where they can be updated/checked/unchecked.

I also tried this, without the .option value:

```
{% set email_preferences = craft.app.fields.getFieldByHandle('email_preferences') %}
																				
{% for option in email_preferences %}
	{{ option.selected }}
{% endfor %}
```
No luck though, getting: Key "selected" for array with keys "0, 1, 2" does not exist.

Thanks in advance.

**Comment by brandonkelly** [comment]
OK so this is for users, not entries, but still, you should be going through the _user_ to get the checkbox options; not getting the field itself via `craft.app.fields`.

```twig
{# this hidden input is required so that *something* will be posted if they uncheck all the boxes #}
<input type="hidden" name="fields[email_preferences]" value="">

{% for option in currentUser.email_preferences.options %}
  <label>
     <input
       type="checkbox"
      name="fields[email_preferences][]"
      value="{{ option.value }}"
      {% if option.selected %}checked{% endif %}
    >
    {{ option.label }}
  </label>
{% endfor  %}
```
