### ISSUE TITLE
Extra back arrow on Twig Primer link on Cache page

### ISSUE THREAD

**Issue by mlathrom** [craftcms/docs#124]
On the back button that leads to the Twig Primer on the Cache page, there's an extra back arrow.

<img width="160" alt="twig-primer-arrow" src="https://user-images.githubusercontent.com/373889/40572297-1cf49b38-605d-11e8-87b7-c9497c79772c.png">

**Comment by brandonkelly** [comment]
Looks like this is resolved now.
