### ISSUE TITLE
Broken Security Policy Link in Knowledge Base

### ISSUE THREAD

**Issue by bencroker** [craftcms/docs#126]
The Knowledge Base Security FAQ has a broken link to the [Security Policy](https://github.com/craftcms/cms/security/policy) at:
https://craftcms.com/knowledge-base/security-faq#ive-found-a-security-vulnerability-how-should-i-report-it

Reporting here since this is outside this repo but related to documentation.

**Comment by mattstein** [comment]
Fixed, thank you @bencroker.
