### ISSUE TITLE
Remove Deprecated `Public-Key-Pins` Header

### ISSUE THREAD

**Issue by bencroker** [craftcms/docs#127]
The Securing Craft page in the Knowledge Base recommends setting the deprecated `Public-Key-Pins` header:
https://craftcms.com/knowledge-base/securing-craft#set-security-headers-for-the-front-end-site

Please consider removing this header, as recommended at https://developer.mozilla.org/en-US/docs/Web/HTTP/Public_Key_Pinning

> This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time.

Reporting here since this is outside this repo but related to documentation.

**Comment by bencroker** [comment]
Please also consider adding the `Expect-CT` header in its place:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expect-CT

**Comment by mattstein** [comment]
Done, thank you @bencroker!
