### ISSUE TITLE
Inconsistent configuration keys in documentation

### ISSUE THREAD

**Issue by monooso** [craftcms/docs#128]
### Description
The [Setting up Tests](https://craftcms.com/docs/3.x/testing/testing-craft/setup.html#step-3-create-required-files) documentation specifies a `dbSetup` configuration setting, which controls how the database is setup before tests. Below the example YAML document is a callout, which points to an explanation of the configuration variables.

However, [the explanation](https://craftcms.com/docs/3.x/testing/framework/config-options.html#config-options) makes no mention of a `dbSetup` configuration setting. Instead, it describes a `setupDb` setting, which appears to serve the same purpose.

[The `craft\test\Craft::$addedConfig` array](https://github.com/craftcms/cms/blob/master/src/test/Craft.php#L77-L84) uses `setupDb`, but [the `setupDb` method uses `dbSetup`](https://github.com/craftcms/cms/blob/master/src/test/Craft.php#L223).

Which is correct? It appears to be `dbSetup`, but I'm not entirely sure.

### Steps to reproduce

1. Read the [Setting up Tests](https://craftcms.com/docs/3.x/testing/testing-craft/setup.html#step-3-create-required-files) documentation.
2. Read the references [config options](https://craftcms.com/docs/3.x/testing/framework/config-options.html#config-options) documentation.

### Additional info

- Craft version: 3.x
- PHP version: N/A
- Database driver & version: N/A
- Plugins & versions: N/A

**Comment by angrybrad** [comment]
`dbSetup` is the correct config setting - i've updated the docs here to reflect https://craftcms.com/docs/3.x/testing/framework/config-options.html#dbsetup and updated https://github.com/craftcms/cms/commit/05f0b95a30dfc93180854b1bf43e221dc213e37a to be consistent. Left this method name the same for backwards compatibility https://github.com/craftcms/cms/blob/master/src/test/Craft.php#L211

Thanks for the report!
