### ISSUE TITLE
Authorizing users in headless mode with React

### ISSUE THREAD

**Issue by mark-wff** [craftcms/docs#129]
### Description

Is there a best practice how a user management with a SPA (Single Page Application) can/should be implemented? Does Craft have to be provided in the same domain or is it also possible to run Craft in a subdomain? 

My current solution is to provide Craft in a subfolder. (Frontend: example.com/ Craft: example.com/craft)
It would be nicer to have a subdomain. (Frontend: example.com/ Craft: craft.example.com)

Important is the possibility to log in and out in the SPA to access certain content.

**Comment by brandonkelly** [comment]
Transferred this over to our docs repo, since this seems mostly like an opportunity to improve headless documentation.

**Comment by mark-wff** [comment]
Would be good if the documentation for headlessMode was more detailed at this point. But I also think that the headless mode for authentication could be improved to talk with Frontend-Frameworks like React and so on.

**Comment by AugustMiller** [comment]
Closing now that #428 is merged!

https://craftcms.com/docs/4.x/dev/controller-actions.html
