### ISSUE TITLE
Explain or drop version field recommendation in composer.json 

### ISSUE THREAD

**Issue by ostark** [craftcms/docs#130]
The plugin docs recommend to maintain the version field for some undocumented reason:

> While not strictly required by Composer, we recommend you explicitly set the version in your composer.json because it makes a couple things easier on you when developing the plugin. 

I'm about to remove the version field from my packages and wonder if there is a good reason to keep it. 

For me it requires double housekeeping of versions which is prone to errors. AFAIK packagist will use the git tag/release if possible.

**Comment by ostark** [comment]
@mattstein no opinion on this topic?

**Comment by mattstein** [comment]
@ostark I wondered the same thing when you asked, and it sounds like leaving the version in composer.json is still useful if you end up including `path` repositories.

**Comment by ostark** [comment]
Locally you probably want to use the latest code in the working directory (path) of the plugin.

That's the behavior when you use `"me/my-plugin": "*"`. ~~Or you want to use a specific branch, which is possible with `"me/my-plugin": "dev-somefeature".~~.

It happened more than once to me, that I forgot to update the "version" in the composer.json of the package before tagging it and releasing it.

**Comment by ostark** [comment]
When you require repositories using "path", by default the code is symlinked, which means any change you do with your plugin is directly reflected in the test-project. Using a specific version might be even more confusing than "*" or "dev-master". 

### Example:
You require `me/my-plugin:^1.5.0` in your test-project using a local "path". Then you start working on the "2.0.0" version and specify it in the composer.json of your plugin while working on it. You may think that the package you are working on and require in your test-project is locked to the "^1.50" release, but that's not the case. 

Maybe I'm missing something here to understand the sentence `it makes a couple of things easier on you when developing the plugin.` That's whats this ticket is all about: **Explain or drop the suggestion** :-)

**Comment by mattstein** [comment]
It may make a couple things easier on you, but since nobody knows what they are we’ll get rid of the suggestion. Thanks @ostark!

**Comment by ostark** [comment]
@mattstein Awesome. That was my intention 😀
