### ISSUE TITLE
Warning regarding @web alias

### ISSUE THREAD

**Issue by ccchapman** [craftcms/docs#135]
The `@web` alias is mentioned in the [sites](https://craftcms.com/docs/3.x/sites.html#site-url) and [config](https://craftcms.com/docs/3.x/config/#aliases) documentation pages. The former says to never use `@web` for a site URL, while the latter says you should explicitly declare its value if doing so.

I generally use an explicit `@web` value (i.e. it's synced to a `.env` value in `config/general.php`.) If this is not obsolete or discouraged, maybe the warning message should be revised as such.

**Comment by mattstein** [comment]
Thanks @ccchapman! Just updated the _Sites_ page warning to be consistent with the _Configuring Craft_ note.
