### ISSUE TITLE
Improve “Controllers”

### ISSUE THREAD

**Issue by ericjanofski** [craftcms/docs#140]
I have a suggestion for https://craftcms.com/docs/3.x/extend/controllers.html

I simply cannot understand controller and how to get one to work with only references to foo and bar. I need examples and it's all abstract as though it's written for someone who completely understands the content already. New adopters will struggle and use a different platform if the essential task of calling a controller isn't made possible with good docuementation.

**Comment by mattstein** [comment]
Thanks for the feedback, @ericjanofski! This page is meant for developers extending Craft to add their own controllers—hence the `foo` and `bar` since the plugin itself will dictate whatever the controller is doing.

If you’re looking to call Craft’s existing controllers, they’re documented here:
https://craftcms.com/docs/3.x/dev/controller-actions.html

Several examples there include links with form template examples.

If you’re new to building plugins and it’d help to customize a scaffold to start with, check out [pluginfactory.io](https://pluginfactory.io/) if you haven’t already. I hope this helps!

**Comment by ericjanofski** [comment]
Thanks Matt. i used pluginfactory and created a module. I was able to get a template to auto load for a custom control panel index page. But I'm struggling with getting a controller to load variables. there's nothing here that shows how to register a controller to handle a twig file that's loaded by the cp templates.

**Comment by mattstein** [comment]
Anything can post to a controller as long as it’s compatible with the site CSRF settings and the controller’s authentication requirements (if any) for the relevant action. So there’s no special relationship between Twig and the controller.

If I’m understanding correctly and you’re able to post from your custom control panel template to this controller, but you’re not sure how to access the post parameters, you might be looking for `Craft::$app->getRequest()`. This returns an instance of the [Request class](https://docs.craftcms.com/api/v3/craft-web-request.html).

So if you were including a `foo` parameter in your post, you could get its value with `Craft::$app->getRequest()->getParam('foo')`.

Let me know if I’ve missed your point and I’ll do my best to help!

**Comment by ericjanofski** [comment]
Matt, thank you so much for taking the time to help. After two days I found the answer.

In my modules init i added this:

        Event::on(
            UrlManager::class,
            UrlManager::EVENT_REGISTER_CP_URL_RULES,
            function (RegisterUrlRulesEvent $event) {
                $routes = include __DIR__.'/routes.php';
                $event->rules = array_merge($event->rules, $routes);
            }
        );
        
        and in my modules/src/routes.php this:
        
      return [
      'insights-panel' => 'insightspanel/default/index'
    ];
    
    
    This then started reading the output of my controller named DefaultController.php with an actionIndex
    
    Before adding that to my init my routes were inert.    
    
    Thanks again for taking the time to help.

**Comment by mattstein** [comment]
I’m not sure I did help @ericjanofski, but I’m glad you solved it! :)

Thanks again for taking the time to file an issue here.
