### ISSUE TITLE
Anchor scroll issues in Chrome (v88) and Safari (v14)

### ISSUE THREAD

**Issue by jrrdnx** [craftcms/docs#149]
When navigating to a heading either from a result in the Search bar dropdown, or from the 'On This Page' sidebar menu, the page is scrolled to the wrong location in Chrome (v88). This currently works perfectly for me in Firefox (v85).

Both the Search bar results and the 'On This Page' menu have the same result, but depending on where the anchor tag is on the page it either scrolls not far enough down the page or too far. For instance on this page: https://craftcms.com/docs/3.x/config/config-settings.html#system

- if I click the 'System' link in the sidebar and wait for the page to finish auto scrolling, I then have to scroll _up_ to see that heading (it end up several "scroll pages" above where it actually puts me)
- if I click the 'Assets' link in the sidebar and wait, I then have to scroll _down_ to see that heading as it ends up several "scroll pages" below where it actually puts me
- using the Search bar, searching for terms under the System heading it usually puts me somewhere pretty close to what I'm searching for when it's around the "default..." settings (defaultCpLocale, defaultDirMode, or defaultFileMode)
- when I click on any link in the sidebar and see it hasn't actually scrolled to the correct place, I can click it again and it will scroll closer, and again, and again; it takes about 4-5 clicks to actually get to the right location

Safari (v14) has the same issues as above except for the last one. Since there's no smooth scrolling it doesn't do the additional jumping around on subsequent clicks.

Let me know if I can provide any additional info!

Note: This was only observed on MacOS 10.14

**Comment by mattstein** [comment]
Thanks @jrrdnx! I’ve been battling scroll issues for a while but thought I had them fixed.

Is there any chance your viewport width was consistently >= 1408px in each case you mentioned? If so, does everything behave normally < 1408px?

**Comment by jrrdnx** [comment]
Taking a closer look, yes! It definitely looks like the `zoom` at that breakpoint is the cause. Not to step on any toes, but would setting `font-size: 108%;` on the `html` element work for you? It looks to achieve the same effect without causing any smooth scrolling issues.

**Comment by mattstein** [comment]
The `zoom` visual result is intentional but it causes a number of tricky issues. I wonder if we can get away with adjusting the font size only as you suggest—will keep this open until it’s resolved one way or another.

Thanks for bringing this up so carefully and sharing that idea.

**Comment by jrrdnx** [comment]
No problem, glad to help!

**Comment by mattstein** [comment]
Just updated to use `font-size` instead. Thanks again for the nudge on this @jrrdnx. 🎩

**Comment by jrrdnx** [comment]
Works perfectly, thank you! Always glad to lend a hand.
