### ISSUE TITLE
docs for entry fields page refear to v2 

### ISSUE THREAD

**Issue by astronauta88** [craftcms/docs#152]
I belive docs in this page refears to craft cms v2 instead v3
https://docs.craftcms.com/v3/entries-fields.html

> (this setting only appears if you’re running Craft Pro with more than one site locale

Also, for some reason no page gets selected in orange color on side menu when this page of docs is opened.

**Comment by brandonkelly** [comment]
Thanks for pointing that out!

> Also, for some reason no page gets selected in orange color on side menu when this page of docs is opened.

Yeah currently those pages aren’t part of a nav. On my list to fix that.
