### ISSUE TITLE
Mention predefined patterns in URL rules config

### ISSUE THREAD

**Issue by carlcs** [craftcms/docs#155]
https://docs.craftcms.com/v3/config/#url-rules should mention that you can use predefined patterns `{handle}` and `{slug}`.

**Comment by carlcs** [comment]
Now that you updated it I noticed that there’s overlap with the Advanced Routing section in Concept Routing. https://docs.craftcms.com/v3/routing.html#advanced-routing

Probably the better place to document the predefined patterns, with a link to it from the config docs?

And another thing, is `'news/(\d{4})/(\d{2})' => 'news/_archive',` syntax still possible in 3?

**Comment by brandonkelly** [comment]
@carlcs Yeah, thanks for pointing that out. Just rewrote the Routing page (there was a lot of outdated info on it) and now the URL Rules section of the Config Overview page links to it.
