### ISSUE TITLE
includeCssFile/includeJsFile are not documented

### ISSUE THREAD

**Issue by XhmikosR** [craftcms/docs#158]
Do these apply on Craft 3? I tried them and they seem to work, but I don't see them documented in v3 doc functions.

**Comment by XhmikosR** [comment]
Never mind, I just saw the are deprecated :)

**Comment by brandonkelly** [comment]
Yep, they’re listed here: https://docs.craftcms.com/v3/changes-in-craft-3.html#template-tags

**Comment by XhmikosR** [comment]
Yup, all good, and I can pass any attributes I need to, like integrity, crossorigin and async. 😃

**Comment by XhmikosR** [comment]
@brandonkelly: is there any way to change the position of the CSS files which are registered with `{% do view.registerCssFile(url) %}`? I looked into Yii's docs and it doesn't seem possible.

Reason: I use craft-seomatic which renders its HTML head tags before the stylesheet's are rendered.

**Comment by brandonkelly** [comment]
You can customize the place that it gets output by adding a `{{ head() }}` tag to your template.

https://docs.craftcms.com/v3/dev/functions.html#head
