### ISSUE TITLE
Update emails screenshot

### ISSUE THREAD

**Issue by lukeholder** [craftcms/docs#158]
Remove or update the email setup screenshot on this page:

https://craftcms.com/docs/commerce/3.x/order-status-emails.html#creating-an-email

see also https://github.com/craftcms/commerce/issues/2018

**Comment by mattstein** [comment]
This page is also an old duplicate (my fault):
https://craftcms.com/docs/commerce/3.x/order-status-emails.html#creating-an-email

Correct equivalent is the one in the sidebar navigation:
https://craftcms.com/docs/commerce/3.x/emails.html#creating-an-email

**Comment by mattstein** [comment]
Set up a redirect that’ll be active next time we clear out the build cache.
