### ISSUE TITLE
Improve “About Craft Nitro”

### ISSUE THREAD

**Issue by narration-sd** [craftcms/docs#164]
I have a suggestion for https://craftcms.com/docs/nitro/2.x/

There's no information I can find about server ram and disk requirements?

**Comment by mattstein** [comment]
Thanks for the suggestion @narration-sd!

We just updated this page to include minimum and recommended Docker resource settings for Docker Desktop: https://craftcms.com/docs/nitro/2.x/

**Comment by narration-sd** [comment]
Great, Matt - just what was needed!

Thanks much, Clive
