### ISSUE TITLE
Doc enhancement for VSCode users

### ISSUE THREAD

**Issue by MattWilcox** [craftcms/docs#173]
### Description

https://craftcms.com/docs/nitro/2.x/xdebug.html#configuring-vs-code

setting up XDebug in Nitro for VSCode... Step2; create a Launch Configuration... 

If you've never done this before you have no idea what a Launch Configuration is. Could we please link to https://code.visualstudio.com/docs/editor/debugging#_launch-configurations or explain that this means "make a file called launch.json in a folder called .vscode at the root of your project and set the contents to exactly [code]".

Cheers!

**Comment by mattstein** [comment]
Thanks @MattWilcox! Added a link and tip along with a quick screenshot—the UI offers the quickest way to get that initial `launch.json` in place and you can use or ditch those initial `"configurations"` objects it adds for you.

**Comment by MattWilcox** [comment]
Sorry Matt, the code as provided in the docs does not work!

This is what is actually needed...

```
{
	// Use IntelliSense to learn about possible attributes.
	// Hover to view descriptions of existing attributes.
	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Listen for XDebug",
			"type": "php",
			"request": "launch",
			"port": 9003,
			"pathMappings": {
				"/app": "${workspaceRoot}"
			},
			"hostname": "whatever.nitro",
			"xdebugSettings": {
				"max_data": 65535,
				"show_hidden": 1,
				"max_children": 100,
				"max_depth": 5
			}
		}
	]
}
```

Though while this does (finally) get activity in the Debug panel, something was not right as when a breakpoint is hit the following was thrown as an error...

```
Unable to open 'BaseJson.php': Unable to read file '/Users/mattwilcox/nitro/oren/craft/vendor/yiisoft/yii2/helpers/BaseJson.php' (Error: Unable to resolve non-existing file '/Users/mattwilcox/nitro/oren/craft/vendor/yiisoft/yii2/helpers/BaseJson.php').
```

The path mapping is wrong. My VSCode workspace root is NOT the Craft root. My Craft stuff is a subfolder of my VSCode workspace, and so needed to be set accordingly: 

```
"pathMappings": {
				"/app": "${workspaceRoot}/craftProject"
			},
```

May be worth mentioning?

**Comment by mattstein** [comment]
Oh no, that's 100% my fault; definitely tested but neglected to consider how others might structure projects. Will note the importance of that path map—thank you for your patience and perseverance here!

**Comment by MattWilcox** [comment]
No worries Matt, as ever very grateful for the work you all put in. I'm _totally_ new to debugging, but with the above have got it to work in VSCode! Now to learn how to use it... ha!

**Comment by mattstein** [comment]
Added a bit more context and an alternate example. Embarrassingly enough, also replaced a VS Code variable that was deprecated. 😬 

https://github.com/craftcms/docs/commit/4347b0b7ac3456d75af29b3fd6b18095ba13e706
