### ISSUE TITLE
Web Install Clarification

### ISSUE THREAD

**Issue by sbossarte** [craftcms/docs#174]
Portions of the [installation document](https://github.com/craftcms/docs/blob/v3/docs/installation.md) mention going to the following url to perform/verify installation:

```
http://<Hostname>/index.php?p=admin
```

Which only functions if the environment is in `devMode`. Some web installations may occur on domains that do not automatically enable devMode, and instead require directly going to the `admin/install` route.

Could there be some clarification added to either note the `devMode` requirement, or possibly adjusting the URL in this document to include the whole `admin/install` route?

**Comment by brandonkelly** [comment]
There’s no reason going to `http://<Hostname>/index.php?p=admin` would only work when Dev Mode is enabled. Should make no difference.

**Comment by sbossarte** [comment]
I may be misinterpreting how the [craft/web/Application](https://github.com/craftcms/cms/blob/develop/src/web/Application.php) component behaves, but after installing Craft through composer, via `composer create-project craftcms/craft` and attempting to go to `/admin` to run the install process, I would wind up with a Service Unavailable message. I could only get the install screen to appear on the web by going to `/admin/install` explicitly. Is there something else that could be causing this behavior?

**Comment by brandonkelly** [comment]
Doh, I forgot we changed this recently (b18a92c49f2546b429d5fdd4f8b7d88b18a4ce72). Just updated the installation instructions to direct users to go to `admin/install` instead.
