### ISSUE TITLE
Broken links to element controller examples

### ISSUE THREAD

**Issue by lazlo-bonin** [craftcms/docs#178]
The only available links to element controller and template examples are broken:

https://docs.craftcms.com/v3/extend/element-types.html#editing-elements

> craft\controllers\actionEditCategory – renders the Edit Category page
craft\controllers\actionPreviewCategory – renders a category’s front-end page for a Live Preview request
craft\controllers\actionSaveCategory – saves a category
craft\controllers\actionDeleteCategory – deletes a category
craft\controllers\actionShareCategory – handles a Share Category request, creating a token for categories/view-shared-category and redirecting the user to it
craft\controllers\actionViewSharedCategory – renders a category’s front-end page for a Share Category token

Broken link example: https://docs.craftcms.com/api/v3/craft-controllers-actioneditcategory.html

**Comment by brandonkelly** [comment]
Thanks for pointing that out!
