### ISSUE TITLE
Can't select element text if it's a H4

### ISSUE THREAD

**Issue by michaelroper** [craftcms/docs#181]
### Description

It looks like there is a `user-select: none;` style applied to `<h4>` elements in the docs that prevents selecting things like the `utils/repair/section-structure` line in this image:

![image](https://user-images.githubusercontent.com/60287/111575604-b80e3280-87e9-11eb-8190-d18f11ed006a.png)

![image](https://user-images.githubusercontent.com/60287/111575609-bba1b980-87e9-11eb-8e1e-86005ed5cc23.png)

Are you able to either kill that style, or make sure `<code>` elements specifically can always be selected?

**Comment by mattstein** [comment]
Yikes! There was some real shoddy scoping in a totally unrelated footer component. Thank you for pointing this out and apologies for the blunder.
