### ISSUE TITLE
Size of sidebar and text

### ISSUE THREAD

**Issue by peteeveleigh** [craftcms/docs#183]
This seems really picky but could the sidebar of the Class Reference docs be made slightly wider and the font made slightly smaller?
Currently it's looking like:
![Screenshot 2021-03-23 at 10 12 47](https://user-images.githubusercontent.com/827065/112130969-ee202d80-8bc0-11eb-982d-69a689eb716a.png)

With a small tweak to give the sidebar a width if 25rem and the .sidebar-heading class a font-size:1rem it cleans it up so much! 
![Screenshot 2021-03-23 at 10 14 15](https://user-images.githubusercontent.com/827065/112131126-1dcf3580-8bc1-11eb-8d32-2aa5edc3431c.png)

**Comment by peteeveleigh** [comment]
I've just seen that this repo doesn't include the Class Reference docs but I don't know where I should request a change to those.

**Comment by mattstein** [comment]
You’re right on both counts: that sidebar text does fit better, and this repo’s a different thing. The class reference uses [pixelandtonic/vuepress-theme-craftdocs](https://github.com/pixelandtonic/vuepress-theme-craftdocs), and apparently one cannot transfer an issue across organizations.

So I did some old-fashioned copy-and-paste kung foo: https://github.com/pixelandtonic/vuepress-theme-craftdocs/issues/24

There are two challenges here:

1. Others rely on this theme so there’d need to be a gentle, opt-in way of changing the font size to avoid surprising anyone.
2. Our class reference generation pipeline is currently broken, so I’d have no way of having this change take effect for the live documentation—which is kind of the point.

Can only solve for one of those right now so this may have to wait.
