### ISSUE TITLE
Image transform via image editor not showing up in live preview

### ISSUE THREAD

**Issue by janhendrickx** [craftcms/docs#183]
If you edit an image with the image editor in Craft, it isn't rendered in the live preview; It needs to be saved first (and of course the page needs to be refreshed) before you get to see it. 
It would be handy if the edited version is shown in the live preview - if possible.

**Comment by angrybrad** [comment]
Sounds like a good feature request... would you mind posting it over on the CMS repo at https://github.com/craftcms/cms/issues instead of this docs repo?
