### ISSUE TITLE
Can't installl v3.0.0-beta 13

### ISSUE THREAD

**Issue by Danetag** [craftcms/docs#19]
Hello!

I'm running into this issue when I'm trying to install the latest version with composer 

<img width="882" alt="screen shot 2017-05-02 at 3 38 44 pm" src="https://cloud.githubusercontent.com/assets/810008/25635821/776ddf30-2f4d-11e7-9ffb-017378f75a15.png">

Am I doing anything wrong?

Thanks!

**Comment by brandonkelly** [comment]
Yep already covered by https://github.com/craftcms/cms/issues/1681. We are getting out a fix soon.
