### ISSUE TITLE
Would it be possible to modify the way the left scroll bar and drop down menus look?

### ISSUE THREAD

**Issue by xyeLz** [craftcms/docs#197]
The theme is fantastic, but the left scrollbar and drop down menus still render in an ugly box format, despite whether I use Edge, Chrome, or Firefox. Would it be possible to update this to be more modern?

**Comment by AugustMiller** [comment]
We have a number of aesthetic and accessibility improvements under review, but for now, the native browser functionality will have to remain. As a reflection of our priorities with the Craft control panel, we will generally try and use native features unless there is a significant UX penalty, which I don't see here.
