### ISSUE TITLE
Nested permissions syntax missing

### ISSUE THREAD

**Issue by OldStarchy** [craftcms/docs#2]
This page shows how to define nested permissions but doesn't have information on how to check for them.

https://docs.craftcms.com/v3/extend/user-permissions.html

eg. for this example
```php
'permissionName' => [
    'label' => 'Permission Label',
    'nested' => [
        'nestedPermissionName' => [
            'label' => 'Nested Permission Label',
        ],
    ],
];
```

its not clear which of the following is correct (if any)
```php
$user->can('nestedPermissionName');
$user->can('permissionName.nestedPermissionName');
$user->can('permissionName/nestedPermissionName');
```

**Comment by mattstein** [comment]
I’m just learning this too, @aNickzz! [Looks like you were close](https://github.com/craftcms/cms/blob/7b89c4ad2f6250d0415b0fb22955576f685e0e25/src/helpers/Cp.php#L90-L90) and the answer is `:`:

```php
$user->can('permissionName:nestedPermissionName');
```

Adding a note now, thanks for bringing this up!

**Comment by mattstein** [comment]
...and I’m totally wrong. Your first answer is the correct one:

```php
$user->can('nestedPermissionName');
```

It turns out the nesting is purely for UI and Craft’s use of `:` is its own convention for namespacing. You’ll always want to refer to the key of the relevant permission, and all the keys in the permissions array should be unique. Sorry for the (my) confusion!

**Comment by mattstein** [comment]
Corrected documentation error in https://github.com/craftcms/docs/commit/e96200acad5667aa3946dd96c15e91dc68be2f41.

**Comment by OldStarchy** [comment]
Thanks @mattstein :)
