### ISSUE TITLE
Clarify the docs for "displaying entries related to a category"

### ISSUE THREAD

**Issue by MattWilcox** [craftcms/docs#213]
### Description

https://craftcms.com/knowledge-base/displaying-entries-related-to-a-category

Nothing here is wrong, but it does not specify this code works only on a Category page, and is written such that you could easily interpret the "subject" of the article being an Entry and not a Category. It's not specified how "this category" is defined.

Someone in Discord was expecting this to work on an Entry page, having Craft "magically" know what category the Entry belonged to. From their perspective, reading this, that does make sense.

Maybe specify that this code relies on being used on a Category page, and offer an example of how you could get a Category to relate with from an Entry page?

**Comment by mattstein** [comment]
Thanks for this, @MattWilcox! 

I just [updated that page](https://craftcms.com/knowledge-base/displaying-entries-related-to-a-category) to clarify the context for that first example, add another for _selecting_ the category with a link to querying categories, and for completeness one more demonstrating category selection via field handle—again linking to the relevant docs.

I’m hoping this eliminates any ambiguity without being too verbose. Seems much better to me, but let me know if you disagree!
