### ISSUE TITLE
[Safari] No redirects in same tab

### ISSUE THREAD

**Issue by carstenjaksch** [craftcms/docs#215]
### Description

On [Core Concepts](https://craftcms.com/docs/commerce/3.x/core-concepts.html), the links _Adjusters_ and _Events_ do not redirect on normal click and throw a 404.

Opened in a new tab or reloading the 404 page and the redirects to `extend` work as expected.

Tested in latest Safari and Chrome. Only the latter works in both cases.

### Steps to reproduce

1. Go to [Core Concepts](https://craftcms.com/docs/commerce/3.x/core-concepts.html) in Safari.
2. Open the links to _Adjusters_/_Events_ in a new tab (CMD+Click).
3. Works.
4. Open the same links without CMD-clicking, 404 (open in same tab).
5. Reloading redirects then (lol).

🖖

**Comment by mattstein** [comment]
How bizarre. Thanks for pointing this out, @cajakre!

**Comment by mattstein** [comment]
Hmm. Somebody fixed something, but it wasn’t me. No longer seeing this and closing since it’s magically resolved itself.
