### ISSUE TITLE
Path to config files not correct

### ISSUE THREAD

**Issue by duur222** [craftcms/docs#22]
In the Configuration chapter, the paths to the default configurations are not correct (anymore)

Example:
vendor/craftcms/cms/src/config/defaults/general.php

Should be:
vendor/craftcms/cms/src/config/GeneralConfig.php

**Comment by takobell** [comment]
Fixed in https://github.com/craftcms/docs/commit/27e3e1a1085befe89511b4f4466e61c9a2261d00
