### ISSUE TITLE
Improve “Installation”

### ISSUE THREAD

**Issue by llanito** [craftcms/docs#236]
1. The working is ambiguous
2. 
Step 5: Set up the Web Server
Create a new web server to host your Craft project. Its document root (or “web root”) should point to your web/ directory (or whatever you’ve renamed it to).

The reference to web/ directory should explicitly refer to "Craft CMS install web directory" rather than "your web" directory which means nothing really. 

I have a suggestion for https://craftcms.com/docs/3.x/installation.html

**Comment by mattstein** [comment]
Thanks for the feedback, @llanito.

I’m struggling to understand what could be improved here. In the [Directory Structure](https://craftcms.com/docs/3.x/installation.html#directory-structure) section further up the page we look at the files you’ll get for a default Craft install, specifically calling out that `web/` folder:

<img width="740" alt="Screen Shot 2021-07-05 at 08 59 40 AM@2x" src="https://user-images.githubusercontent.com/2488775/124482884-5c06f400-dd6f-11eb-931a-76512894ca09.png">

So when you say it “means nothing really,” I’m not sure what you mean by that unless that callout is unclear. (You might have chosen to rename it or reorganize the file layout, which we also address.)

Everything we’re doing on this page is in the context of a Craft CMS installation, so I’m also not understanding what the phrase “your Craft CMS install `web/` directory” is clarifying.

Am I missing your point?

**Comment by mattstein** [comment]
Closing since I’ve not heard back, but happy to return to this if I can understand the problem!
