### ISSUE TITLE
Updates for orders' shipping method 3.x

### ISSUE THREAD

**Issue by lukeholder** [craftcms/docs#241]
An update top "Fetching a Cart’s Shipping Method"

https://craftcms.com/docs/commerce/3.x/extend/shipping-methods.html#fetching-a-cart-s-shipping-method

### Description

Craft no longer sets the default (cheapest) shipping method when calling `order.getShippingMethod()`. That can statement be removed. It did not make sense for the method to set the default since it would also not save the selection to the order. This was seen as a bug. It is now consistent with `order.shippingMethodHandle`

Recommend front-end templates use:

`order.shippingMethodHandle` and
`order.shippingMethodName`  (which is populated from the selected sipping method handle set on the order)

This allows you to avoid calling `order.getShippingMethod().name` in your templates (which could be more expensive to retrieve)

**Comment by mattstein** [comment]
Updated! Decided against pointing out `order.getShippingMethod().name` as less performant since I’m not sure what benefit it would have over a solid, simple recommendation as you put it.
