### ISSUE TITLE
"Creating an ​“Archive” Page for Entries" no longer works

### ISSUE THREAD

**Issue by darylknight** [craftcms/docs#243]
Partway down [this page](https://craftcms.com/knowledge-base/creating-an-archive-page-for-entries), it refers to this code example:

```twig
<h1>{{ year }}</h1>

{% set entriesInYear = craft.entries()
    .section('blog')
    .after(year)
    .before(year+1)
    .all() %}

{% for month, entries in entriesInYear|group("postDate|date('F')") %}
    <h2>{{ month }}</h2>
    <ul>
        {% for entry in entries %}
            <li>{{ entry.getLink() }}</li>
        {% endfor %}
    </ul>
{% endfor %}
```

This no longer outputs any results. Looking through [the docs](https://craftcms.com/docs/3.x/entries.html#before), `.after` and `.before` require either a `dateTime` object, or a string formatted as `YYYY-MM-DD`: 

I think that article needs to be amended to something like this?:

```{% set entriesInYear = craft.entries.section('blog').after(year ~ '-01-01').before((year + 1) ~ '-01-01').all() %}```

**Comment by mattstein** [comment]
Thanks @darylknight! Someone also pointed this out in Discord—will get this sorted and follow up.

**Comment by mattstein** [comment]
Craft [3.7.6 is out](https://github.com/craftcms/cms/blob/main/CHANGELOG.md#376---2021-07-27) with a fix for this. Thanks again @darylknight!
