### ISSUE TITLE
Documentation: previewTokenDuration not present in Class Reference and not working

### ISSUE THREAD

**Issue by CaitlinWeb** [craftcms/docs#251]
### Description

On the General Config documentation page there is a setting defined called [`previewTokenDuration`](https://craftcms.com/docs/3.x/config/config-settings.html#previewtokenduration). However, [in the class reference there is no setting with that name](https://docs.craftcms.com/api/v3/craft-config-generalconfig.html#property-previewtokenduration). 

I set this value to an integer (in seconds) but the preview link is still expiring before the value I set.

I believe the correct setting to use is `defaultTokenDuration`. This should be fixed in the documentation.

### Steps to reproduce

N/A

### Additional info

- Craft version: 3.6.15
- PHP version: 7.4.23
- Database driver & version: N/A
- Plugins & versions: N/A

**Comment by mattstein** [comment]
Sorry for the confusion, @CaitlinWeb!

The `previewTokenDuration` config setting was [added in Craft 3.7.0](https://github.com/craftcms/cms/blob/main/CHANGELOG.md#370---2021-07-13), specifically so [preview durations could be separate from other site security settings](https://github.com/craftcms/cms/issues/2394).

So `defaultTokenDuration` is the correct setting for Craft 3.6.15.

Lastly, the class reference is out of date while we’re fixing issues with the generator—so while [previewTokenDuration is real](https://github.com/craftcms/cms/blob/main/src/config/GeneralConfig.php#L1176-L1185), it’s not reflected there yet.

**Comment by CaitlinWeb** [comment]
Thank you for clarifying, @mattstein! Makes sense. When we upgrade to 3.7 `previewTokenDuration` will be very useful!
