### ISSUE TITLE
Uncaught Error: Cannot find module 'ansi-html'

### ISSUE THREAD

**Issue by nirali35** [craftcms/docs#254]
### Description
There seems to be some problem running this project. This following error is shown in the browser console. This is while trying to run the project as is without any modification on a macOS.
```
Uncaught Error: Cannot find module 'ansi-html'
    at webpackMissingModule (overlay.js?2ac6:4)
    at eval (overlay.js?2ac6:4)
    at Object../node_modules/webpack-dev-server/client/overlay.js (app.js:6672)
    at __webpack_require__ (app.js:833)
    at fn (app.js:130)
    at Object.eval (client?cae4:10)
    at eval (index.js?http://0.0.0.0:177)
    at Object../node_modules/webpack-dev-server/client/index.js?http://0.0.0.0 (app.js:6660)
    at __webpack_require__ (app.js:833)
    at fn (app.js:130)
```

### Steps to reproduce
1. npm i
2. npm run docs:dev
3. Open localhost:8080/docs

Actual: Notice nothing renders on the page and the console shows the above error.
Expected: Load the home page

**Comment by nirali35** [comment]
@mattstein you may have an insight on this

**Comment by mattstein** [comment]
I’m able to run everything fine locally—are you using node 14? (Specified in [.nvmrc](https://github.com/craftcms/docs/blob/main/.nvmrc) but easy to miss.)

**Comment by nirali35** [comment]
Yes, I am using node 14.16.0. And I see this issue on two different machines. Are you able to try running it after reinstalling your packages? Thanks

```
npm -rf node-modules/
npm rm package-lock.json
npm install
```

**Comment by mattstein** [comment]
I can definitely reproduce the problem on two different machines—working on untangling dependencies and will follow up when I can get to the bottom of it.

**Comment by mattstein** [comment]
@nirali35 Would you mind checking out https://github.com/craftcms/docs/tree/feature/prune-dependencies and letting me know if you can build and run that successfully?

```
rm -rf node_modules && rm package-lock.json && npm install
```

Should be able to...

1. `npm run docs:dev` and visit https://localhost:8080 to see working, error-free docs in browser.
2. `npm run docs:build` successfully, which should end rendering sitemap pages:
    ```
    > @ docs:sitemap /Users/whoever/dev/docs
    > vuepress-sitemap -H https://craftcms.com/docs/ -d docs/.vuepress/dist/docs -e /3.x/fr/**


     SITEMAP  Generating sitemap...

     SITEMAP  found 562 locations

     SITEMAP  excluded 118 locations

     SITEMAP  562 locations have been written.
    ````

**Comment by nirali35** [comment]
@mattstein that fixed it! Thx

**Comment by devarsh10** [comment]
> Yes, I am using node 14.16.0. And I see this issue on two different machines. Are you able to try running it after reinstalling your packages? Thanks
> 
> ```
> npm -rf node-modules/
> npm rm package-lock.json
> npm install
> ```

Worked for me. Thank you very much @nirali35
