### ISSUE TITLE
Plugin CP nav item method versus event

### ISSUE THREAD

**Issue by putyourlightson** [craftcms/docs#26]
The [updating plugins to Craft 3 page](https://github.com/craftcms/docs/blob/master/en/updating-plugins.md#modifycpnav) says to use the `EVENT_REGISTER_CP_NAV_ITEMS` event in place of the `modifyCpNav()` method, however the new `getCpNavItem()` method in Craft 3 seems like a better way to do this.

The `modifyCpNav()` method should probably also be added to the [Control Panel Section page](https://github.com/craftcms/docs/blob/master/en/cp-section.md).

**Comment by brandonkelly** [comment]
Well `getCpNavItem()` works pretty much the same as it did in Craft 2 – which is the better option for most plugins. But if a plugin wanted to actually make modifications to the nav (which the `modifyCpNav` hook was for in Craft 2), the `EVENT_REGISTER_CP_NAV_ITEMS` event is the way to do it.

**Comment by khalwat** [comment]
Found this via Google... because the old method of just setting a `subnav` variable in your plugin's templates doesn't seem to work anymore for adding subnav sections in a plugins CP nav.

I assume the correct way to do it would be to override `getCpNavItem()` in my plugin?

`cp.html` just iterates through `craft.cp.nav`:

```
                {% for item in craft.cp.nav() %}
                    {% set hasSubnav = (item.subnav is defined and item.subnav) %}
```
...which is propagated via `cp.php` which just calls that plugin method to build up the array:

```
        // Add any Plugin nav items
        /** @var Plugin[] $plugins */
        $plugins = Craft::$app->getPlugins()->getAllPlugins();

        foreach ($plugins as $plugin) {
            if (
                $plugin->hasCpSection &&
                Craft::$app->getUser()->checkPermission('accessPlugin-'.$plugin->id) &&
                ($pluginNavItem = $plugin->getCpNavItem()) !== null
            ) {
                $navItems[] = $pluginNavItem;
            }
        }
```
I'm also assuming that the `selectedSubnavItem` template variable also is ignored/deprecated?

**Comment by brandonkelly** [comment]
Looks like `cp.html` is still checking the `selectedSubnavItem` variable.

**Comment by khalwat** [comment]
Yes, it is. But it's not checking `subnav` -- which it used to check in Craft 2.x

**Comment by brandonkelly** [comment]
K, will look into it.

**Comment by khalwat** [comment]
I ended up just doing this instead:

```
    /**
     * @inheritdoc
     */
    public function getCpNavItem()
    {
        $navItem = parent::getCpNavItem();
        $navItem = array_merge($navItem, [
            'subnav' => self::ADMIN_CP_SECTIONS,
        ]);

        return $navItem;
    }
```

...which works fine. It just isn't documented anywhere (that I'm aware of), and it might trip up some people who are expecting it to work as it did in 2.x.

I actually prefer it this way, at least some some extent.

**Comment by brandonkelly** [comment]
Ah gotcha… thought you were saying that there was a bug with `selectedSubnavItem`. Right, `cp.html` doesn’t care about a `subnav` variable anymore. Just [documented](https://github.com/craftcms/docs/blob/master/en/cp-section.md#giving-your-plugin-section-a-subnav) how to add subnavs so it’s clear for the next poor soul.

**Comment by bertoost** [comment]
It's not up to date anymore I guess? Seems like `getCpNavItem()` isn't used anymore

**Comment by khalwat** [comment]
@bertoost It's used in plugins still. I'd imagine a module would need to listen to some event.
