### ISSUE TITLE
Documentation on integrating with Events is lacking.

### ISSUE THREAD

**Issue by acalvino4** [craftcms/docs#264]
### Description
As a new craft developer, I can't seems to find good instructions on how to hook into the the craft lifecycle by searching for 'hook' or 'event' as shown in below screenshots. None of the search results are really about lifecycle hooks.

![image](https://user-images.githubusercontent.com/43254861/139487221-47cb5caa-b354-47eb-9928-990bae8ff812.png)
![image](https://user-images.githubusercontent.com/43254861/139487387-09310b07-f5b3-44c3-b1b1-aa8a155dbecf.png)

There are allusions to the ability to do it, such on on [this page](https://craftcms.com/docs/3.x/extend/), but the words most people would probably search don't seem to bring anything up.

A google search for the same reveals
[Craft 2 docs on what I'm looking for](https://craftcms.com/docs/2.x/plugins/hooks-and-events.html)
[Craft Commerce docs on the kind of thing I'm looking for](https://craftcms.com/docs/commerce/3.x/extend/events.html)
[A maybe related kind of hook?](https://craftcms.com/docs/3.x/extend/template-hooks.html) - but I'm pretty sure it's different.

A discussion on the craft discord let me to where I could find the available events in the class reference:
![image](https://user-images.githubusercontent.com/43254861/139488457-d02783db-3512-4ac3-b1c6-2ea803c3c01b.png)

And some further digging led me to this [knowledge base article](https://craftcms.com/knowledge-base/custom-module-events)

Between those last two, I think I can piece together how to hook into craft's lifecycle. But figuring this out and finding the right information has been far more difficult than I think it should be.

Proposal:
We add pages to the craft 3 docs that synthesize this information and provide the equivalent of what these pages described in craft 2. This new page should probably be on of the first two results when searching for 'hook' or 'event' in the docs:
https://craftcms.com/docs/2.x/plugins/hooks-and-events.html
https://craftcms.com/docs/2.x/plugins/hooks-reference.html
https://craftcms.com/docs/2.x/plugins/events-reference.html

Background:
I'm a new craft developer, and while I actually don't have an immediate use case I am trying to solve with hooks, I am on the verge of convincing my company to transition from EE to more craft work. Knowing there is a robust hooks system (that I can preferably figure out without searching through source code) is very important for us if we are to transition.

**Comment by mattstein** [comment]
Thanks for calling this out, @acalvino4! There are a _lot_ of events you can take advantage of with Craft 3, along with some conditions to be aware of specifically for elements. We happen to finally be working on this right now, not _exactly_ in the format you’ve proposed but it should tick all the boxes here. I’ll leave this issue open with the hope of resolving it in the near future.

**Comment by acalvino4** [comment]
Thanks Matt!

**Comment by AugustMiller** [comment]
For folx coming in new—something that I often forget is that events in Craft are almost entirely a Yii concept, so part of the challenge in the learning + discovery phase is figuring out what events are inherited from Yii classes, vs. what Craft provides. Yii alone has [164 "eventable" subclasses](https://www.yiiframework.com/doc/api/2.0/yii-base-component)!

An example I think of pretty frequently is from Commerce, when for a moment (in v2, remove in v3) there was a dedicated event emitted by `Address` models to register custom validation rules, when it was possible all along with the underlying `Model::EVENT_DEFINE_RULES`… even now, looking it up, I fully expected `EVENT_DEFINE_RULES` to be provided by Yii, but much to my chagrin—it's part of Craft's subclass!

Excited to see how this evolves! 😀

**Comment by mattstein** [comment]
The sheer number of events means an exhaustive, hand-edited page is hilariously unfeasible. But we’ll have something sensible to publish soon.

**Comment by mattstein** [comment]
Just launched a new Events page here: https://craftcms.com/docs/3.x/extend/events.html
