### ISSUE TITLE
Best practices for Template Variables

### ISSUE THREAD

**Issue by putyourlightson** [craftcms/docs#27]
Since ["Template variables are no longer a thing in Craft 3"](https://github.com/craftcms/docs/blob/master/en/updating-plugins.md#template-variables), what are the suggested best practices for which classes to make available to templates? For example, should we be creating a variable class as with Craft 2 or a service class specifically for template access? I realise there may not be a definitive answer to this, but some direction would be very helpful :)

**Comment by brandonkelly** [comment]
Use the new `EVENT_INIT` event on the `CraftVariable` class to be notified when it is instantiated, and then you can register your “Variable” class using its `set()` method. The example [in the docs](https://github.com/craftcms/docs/blob/master/en/updating-plugins.md#template-variables) outlines how you’d do that.
