### ISSUE TITLE
Creating too many Block Types in Matrix Fields results in 1118 Row size too large 

### ISSUE THREAD

**Issue by kethmars** [craftcms/docs#28]
***Hey guys!***

Thank you for creating such an awesome CMS. Truly wonderful to build stuff with it, but as always, sometimes some external advice is needed :slightly_smiling_face: .

***Summary:*** We are building a site where we take advantage of the matrix field. The problem is that we need to create loads of columns into _Matrix table_ and some of those columns’ fields may contain very long _JSON_ values(~1200 lines of JSON).
Unfortunately, by doing so, we get the following error
```
SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
The SQL being executed was: ALTER TABLE `matrixcontent_components` ADD `field_authorBlock_authorBlockLanguagesExcluded` varchar(255)
```

***More specifically:*** We have a custom components importer plugin that based on a _JSON_, creates _Matrix’s Block Types_. Each _Block Type_ is a component that has sub-fields with different values. Among other fields, each component has 2 _MultiSelect_ fields that’s value is a list of all the countries in the world. In the database, in components’ _Matrix_ table, a column is created for each components’ field.
As every component has 2 _MultiSelect_ fields with a list of all the countries, the database table row becomes really big, thus giving us the error.

***Question:*** How should we tackle the problem if slicing the matrix into sub-matrixes is not a possible solution? We tried to convert the fields that have long JSON from varchar(255) to TEXT but it did not help and as much as I understood, converting to BLOB is not possible in Craft/Yii.

**Comment by pandt-aws** [comment]
Going to close this as it isn't documentation related (this is the Craft 3 docs repo). But this is probably a better question for the Craft Stack Exchange site anyway: https://craftcms.stackexchange.com. Can you post there are clarify if you're using Craft 2 or Craft 3?

**Comment by takobell** [comment]
Going to close this as it isn't documentation related (this is the Craft 3 docs repo). But this is probably a better question for the Craft Stack Exchange site anyway https://craftcms.stackexchange.com.  Can you post this there are clarify if you're using Craft 2 or Craft 3?
