### ISSUE TITLE
Documentation Around Using AJAX with Craft/Commerce

### ISSUE THREAD

**Issue by simeon-smith** [craftcms/docs#29]
### Description

It would be great to have documentation around the endpoints that accept AJAX requests and the information they accept and return.

**Comment by mattstein** [comment]
Thanks for the issue @simeon-smith, we have these now!

The Craft CMS [Controller Actions](https://craftcms.com/docs/3.x/dev/controller-actions.html) page is live, and there’s one for Commerce that’s ready to be published along with v3.3: https://github.com/craftcms/docs/blob/next/commerce/docs/commerce/3.x/dev/controller-actions.md

We’ve also updated the jQuery and Axios examples here:
https://craftcms.com/docs/commerce/3.x/orders-carts.html#fetching-a-cart

**Comment by yalamber** [comment]
@mattstein would it be possible to add how we can make these request in headless environment where our origins might be different domains or subdomains?

**Comment by mattstein** [comment]
@yalamber Seems like that’d be a matter of configuring CORS appropriately so the browser is cool with it. (Which would also be relevant for live preview and other aspects of using Craft CMS or Craft Commerce.) Might be useful to take a look at this Knowledge Base article which roughly gets there: https://craftcms.com/knowledge-base/live-preview-alternate-control-panel-domain
