### ISSUE TITLE
Get Config Code Sample

### ISSUE THREAD

**Issue by putyourlightson** [craftcms/docs#30]
The way one gets a config setting has changed in Craft 3 and this should be added as an individual code sample in the docs.

Also, the _New_ code in the [getCpAlerts](https://github.com/craftcms/docs/blob/adf409846292dc7f35f79e0a19dbdc4defd33e20/en/updating-plugins.md#getcpalerts) section gives an example, however it incorrectly reads:

`if (\Craft::$app->config->get('devMode')) {`

which should be:

`if (\Craft::$app->config->getGeneral()->devMode) {`

**Comment by brandonkelly** [comment]
Done and done!

**Comment by putyourlightson** [comment]
Thanks!
