### ISSUE TITLE
Register Element Action Type documentation

### ISSUE THREAD

**Issue by Anubarak** [craftcms/docs#31]
Hello 

I'm new to craft 3 so maybe I missed something or I understood something wrong but the code documented in this file [https://github.com/craftcms/docs/blob/master/en/element-action-types.md](url) did not work for me.

`Event::on(Entry::class, Element::EVENT_REGISTER_ACTIONS, function(RegisterElementActionsEvent $event)`
Did not register any event for me

instead 
`Event::on(Element::class, Element::EVENT_REGISTER_ACTIONS, function(RegisterElementActionsEvent $event)` 
Did the trick and created a new option in the default entry index page. Could you eventually explain what to use when?

**Comment by brandonkelly** [comment]
They should both work, but registering it for `Element::class` will register the action for every element type, not just entries.

If `Entry::class` is still not working for you, feel free to send your plugin over to support@craftcms.com and we can take a look at it.
