### ISSUE TITLE
Restructure 'Extending Craft' pages

### ISSUE THREAD

**Issue by dougstjohn** [craftcms/docs#32]
The current page structure for plugin/module extension is confusing for someone who never worked with Craft2 and only cares about extending Craft3.

Referencing: https://docs.craftcms.com/v3/extend/updating-plugins.html

A lot of the important Craft3 extension information is under 'Updating Plugins for Craft 3' and the content references both v2 and v3. This assumes you know v2 and are migrating to v3. This made sense when v3 launched, but a new Craft3 dev today should be able to learn v3 without seeing anything about v2.

**Recommendations:**
- Leave the existing pages in place to help people migrate to v3.
- Copy the whole 'Updating Plugins for Craft 3' section as a new top-level 'Core Concepts' item, remove references to v2, and add content for anything not covered for v3.

**Comment by mattstein** [comment]
We’ve launched new docs that should greatly help ease navigation, clearly separated out the _Extending Craft_ section, and reorganized to make a variety of things—including upgrading and core concepts—easier to find and read. Closing this, but let me know if the restructuring *isn’t* helpful!
