### ISSUE TITLE
Improve “Plugin Development”

### ISSUE THREAD

**Issue by trevorjpuckett** [craftcms/docs#320]
I have a suggestion for https://craftcms.com/docs/2.x/plugins/:
this page is literally empty at the time i am looking at it.

I also cant seem to find any documentation on tasks for 2.x

**Comment by mattstein** [comment]
That’s an empty page, alright! 🤦‍♂️ 

Do you recall how you wound up there, @trevorjpuckett? The _Plugin Development_ sidebar link should land you directly at the Introduction page of that section.

We don‘t have tasks covered in the 2.x documentation, but Brandon’s answer on Stack Exchange will probably be useful if you haven’t seen it already: https://craftcms.stackexchange.com/a/14532/22

**Comment by AugustMiller** [comment]
We are planning to expand the footprint of the plugin + module development documentation for supported versions of Craft, but are not apt to make further contributions to the 2.x branch unless actively misleading information is discovered that interferes with developers getting plugins updated.
