### ISSUE TITLE
plugin/enable and plugin/disable have same example

### ISSUE THREAD

**Issue by jamiematrix** [craftcms/docs#335]
I was looking how to enable a plugin via CLI and found the example for `craft php plugin/enable` and `craft php plugin/disable` have the same example console messages.
[Disable](https://craftcms.com/docs/3.x/console-commands.html#plugin-disable) | [Enable](https://craftcms.com/docs/3.x/console-commands.html#plugin-enable)

**Comment by mattstein** [comment]
Whoops! Just fixed this @jamiematrix, thank you for pointing that out.
