### ISSUE TITLE
Promote search engine indexing of newer versions

### ISSUE THREAD

**Issue by keyurshah** [craftcms/docs#35]
When i do searches in google, the craft commerce 2 documents appear on top. Can those be blocked in the robots.txt so google will index and prioritize craft commerce 3 in searches?

Thanks!

**Comment by mattstein** [comment]
The freshly-updated docs include a full XML sitemap, and a feature that should help humans and spiders alike: if you follow a link into the docs from a search engine and you’re not looking at the most current version, you’ll get a suggested link at the top of the page to view the most recent version of that document.

This should improve UX and indexing, and we can revisit if that’s not the case!
