### ISSUE TITLE
[4.0 Upgrade guide] Document incompatible behavior when checking for eager loading elements

### ISSUE THREAD

**Issue by wsydney76** [craftcms/docs#353]
### Description

Stumbled over a subtle incompatibility  when checking for the existance of eager loaded elements

````
{% set entries = craft.entries
    .section('film')
    .with('screenings')
.all %}

{% for entry in entries %}
    <h1>{{ entry.title }}</h1>
    {% if entry.screenings %}
        <h2>Screenings</h2>
        {% for screening in entry.screenings %}
            {{ screening.location }} {{ screening.dateAndTime|datetime('short') }}
        {% endfor %}
    {% else %}
        No screening scheduled yet, click [here] to receive notifications
    {% endif %}
{% endfor %}
````

So if you just check against a variable `eagerLoadedSomething` (which the [Twig docs](https://twig.symfony.com/doc/2.x/tags/if.html) say how it should be done), it used to evaluate to `false` for an empty array, and will now always be `true` for a collection object.

That's a bit hard to detect, so imho the upgrade guide should mention to use `.count()` instead.

**Comment by mattstein** [comment]
Thanks for pointing this out, @wsydney76! Looks like `.count()` and `|length` are both safe. Noted in the upgrade guide.
