### ISSUE TITLE
Add nitro init guidance on MariaDB / MySQL

### ISSUE THREAD

**Issue by watershed** [craftcms/docs#354]
### Description

I'm setting up a new MacBook and have reinstalled Nitro, but I was thrown by MySQL not being an option in an Apple Silicon environment, and `nitro init` expecting to me to just know what to do instead.

I _think_ I’m in the right direction with [this tweet](https://twitter.com/schofeld/status/1506234949380329472?s=20&t=rvAIhCs4Yf3C_v9F3BfOQw).

It would be good, I feel, if the [installation Docs](https://craftcms.com/docs/nitro/2.x/installation.html) offered some orientation for people like me familiar with MySQL but unaware of MariaDB.

**Comment by mattstein** [comment]
Sorry about that @watershed, I thought we clarified this but apparently I was wrong. Adding a prominent note!

Thanks for filing an issue.
