### ISSUE TITLE
Improve “Tax”

### ISSUE THREAD

**Issue by peteralewis** [craftcms/docs#355]
I have a suggestion for https://craftcms.com/docs/commerce/3.x/tax.html

This gives no help on displaying or calculating tax and no links to further documentation, it only covers theory of having multiple tax zones, but still doesn't offer any pointers to actually displaying tax pricing in a template.

This would be far more beneficial to include:
```
                        {% set allTaxRates = craft.commerce.taxRates.allTaxRates() %}
                        {% for taxRate in allTaxRates %}
                            {{ taxRate.rate }}<br>
                            {{ taxRate.name }} {{ taxRate.rateAsPercent }}
                        {% endfor %}
```

And talking about the tax rate and pricing would be far more useful than just focusing on tax category. Give a link to the relevant classes so you can see the template options:
https://docs.craftcms.com/commerce/api/v3/craft-commerce-models-taxrate.html#public-properties

**Comment by mattstein** [comment]
Thanks @peteralewis!

The tax page you linked to is meant to introduce the major pieces of Commerce’s tax system, where displaying tax information—as we demonstrate in the [example templates](https://github.com/craftcms/commerce/blob/develop/example-templates/src/shop/cart/index.twig#L233-L267)—is most common for the cart, where a number of factors (customer address, item pricing, promotions, etc.) may influence that taxable subtotal.

Can you help me understand what your Twig example here solves? I could see how illustrating tax output relative to the cart would be useful, but I’m struggling to understand the use case for outputting _every_ tax rate for the customer.

**Comment by peteralewis** [comment]
Hi @mattstein, this seems to be the only documentation in the standard guide/documentation and completely understand it is the grounding for how tax works, but it leaves the reader left with "yes, but how do I implement anything in templates...?", especially as the only template example is:

```
{% for taxCategory in craft.commerce.taxCategories.allTaxCategories %}
  {{ taxCategory.id }} - {{ taxCategory.name }}
{% endfor %}
```

And to be honest, who would output that and what use would that be to a customer? I had to pick out elements from Stack Exchange and from the class documentation (which doesn't have examples if I recall correctly) and which is more comfortable for predominately coders and plugin developers.

In the UK (and most individual countries in Europe), we only have 1 tax rate (although varies on products, not location), so the example may be more relevant to that, but the point of the example is code showing how to get the percentage(s) set, the prices, etc. I'm certainly not saying it's a replacement for the existing example, but something more to help developers/designers start to output something useful in their template.

I wasn't aware of the example commerce template, so shows how badly documented and linked to it is (I've been using Craft since late v1 and Commerce only over the past year).

But the example template you've linked to (which would be useful linked to from the tax page :D) shows in the basket, whereas some online shops in the UK that deal with both trade and public accounts have a toggle showing excluding tax or including tax on the product details or listing pages, and usually have to show the tax rate used. But completely understand this doesn't happen in the US due to the difference in State taxes, unless it was localised and assumed/defaulted to the location of the browser.

**Comment by peteralewis** [comment]
For example....

![Screenshot 2022-03-28 at 21 17 05](https://user-images.githubusercontent.com/134265/160479970-53fad2d6-0916-40b0-a49f-5227cd3ea38f.png)

```
{% if variant.onSale %}
   <del>{{ variant.priceAsCurrency }}</del>
   {{ variant.salePriceAsCurrency }}
{% else %}
   {{ variant.priceAsCurrency }}
{% endif %}
{% if variant.isTaxable %}
    {% set allTaxRates = craft.commerce.taxRates.allTaxRates() %}
    {% for taxRate in allTaxRates %}
        <span>(ex. {{ taxRate.name }})</span><br>
        {{ (variant.price * (1+taxRate.rate))|currency }} <span>(inc. {{ taxRate.name }} @ {{ taxRate.rateAsPercent }})</span>
    {% endfor %}
{% endif %}
```

**Comment by mattstein** [comment]
Got it @peteralewis, thank you!

I realize the “Templating” section on that Tax page is distinctly underwhelming, I just wanted to make sure I understood your goal with that specific example. We link to the example templates pretty liberally, but this is clearly a missed opportunity—in addition to some _currently lacking_ examples.

Thanks for taking the time to file the issue and elaborate. Will improve this page.

**Comment by peteralewis** [comment]
I'm assuming I could have used:

```
{% set singleTaxRate = craft.commerce.taxRates.allTaxRates().one() %}
```

**Comment by mattstein** [comment]
Unfortunately not, that’d land you with:

> Twig\Error\RuntimeError: Impossible to invoke a method ("one") on an array.

Because `.one()` is a method you’d use on an element query, and `allTaxRates()` returns an array. You could use the [`|first`](https://craftcms.com/docs/3.x/dev/filters.html#filter) filter, though:

```twig
{% set singleTaxRate = craft.commerce.taxRates.allTaxRates()|first %}
```

You could also fetch the rates for a specific zone, if that helps narrow things, using `taxRatesForZone()` or `taxRatesByTaxZoneId()`:

```twig
{% set rates = craft.commerce.taxRates.taxRatesByTaxZoneId(123) %}
```

Or get a single rate if you already know its ID using `taxRateById()`:

```twig
{% set rate = craft.commerce.taxRates.taxRateById(123) %}
```

Working on revisions to this page that’ll include these and more examples!

**Comment by mattstein** [comment]
Just published a significant update to the Tax page: https://craftcms.com/docs/commerce/3.x/tax.html

The Craft 4 version is nearly the same, but ready to go with the Tax Zone’s new Address Condition field: https://craftcms.com/docs/commerce/4.x/tax.html

This doesn’t literally demonstrate the example you gave, but each tax construct offers Twig + PHP API examples with class reference links so I hope it’ll make it much easier for _anyone_ to get to the specific output they’re looking for.
