### ISSUE TITLE
Improve “Finish setup”

### ISSUE THREAD

**Issue by iuviene** [craftcms/docs#366]
I have a suggestion for https://craftcms.com/docs/getting-started-tutorial/install/setup.html:

Improve the debugging guide for refused database connection.  I followed the guide and I can connect fine using a mysql client inside and outside of the container.  .env settings are correct.  Still can't get to the install screen.

Details:
Needs better debugging (or improved scripts) for fresh install when having issues connecting to db.  Following the instructions I installed mariadb instead of mysql (MacBook Pro with M1).  When trying to hit tutorial.nitro/admin I get a database connection refused error.  

After some troubleshooting realized that I have to change the user and password in the .env to nitro and nitro (instead of root and blank).  I can connect fine manually from outside and inside the container but craft can't.  After searching for solutions I'm at a loss for moving forward.

**Comment by mattstein** [comment]
Thanks for the issue @iuviene!

The `nitro create` command should edit your `.env` file for you, but there’s a [known issue](https://github.com/craftcms/nitro/issues/464) with Nitro and Craft 4 we should have a fix for shortly.

We also have two relevant Knowledge Base articles: one for [investigating failed installs](https://craftcms.com/knowledge-base/troubleshooting-failed-installation) and another specifically for [troubleshooting the database connection](https://craftcms.com/knowledge-base/troubleshooting-database-connection-issues). I’ll link to them from the setup page you mentioned.
