### ISSUE TITLE
Permissions section in docs wrong for 4.x

### ISSUE THREAD

**Issue by timoschwarzer** [craftcms/docs#367]
It sems like the "User permissions" section, specifically the paragraph where all built-in permissions are listed (https://craftcms.com/docs/4.x/user-management.html#permissions), didn't get updated for Craft 4.x. Some permissions have been renamed. (https://craftcms.com/docs/4.x/extend/updating-plugins.html#changed-permissions)

**Comment by mattstein** [comment]
Whoops, you’re right thank you. Just fixed!
