### ISSUE TITLE
[4.x]: Requirements Link for iio/libmergepdf in Documentation

### ISSUE THREAD

**Issue by richhayler** [craftcms/docs#377]
### Description
On https://craftcms.com/docs/commerce/4.x/requirements.html the link to iio/libmergepdf is wrong and should be updated to: https://github.com/hanneskod/libmergepdf

### Craft CMS version
4.0.3

### Craft Commerce version
4.X

**Comment by nfourtythree** [comment]
Hi @richhayler 

Thank you for bringing this to our attention. We will get this fixed.

Thanks!

**Comment by angrybrad** [comment]
Fix is deploying now.
