### ISSUE TITLE
Login is disabled

### ISSUE THREAD

**Issue by moabi** [craftcms/docs#38]
Installing went well, but when I reach this page: http://craft3.dev/admin/login
the login button is disabled
In the console I get a 404 on the svg craft logo
I'm totally new to craft...
Thanks for your help

**Comment by brandonkelly** [comment]
Are you getting any JavaScript errors in your console?

**Comment by moabi** [comment]
not at all, only the login button with the class disabled
Anyway to provide an error log ?

**Comment by brandonkelly** [comment]
Have you typed your password into the form yet?

**Comment by moabi** [comment]
Yes of course, both username & password, and I tried on both chrome & Firefox

**Comment by takobell** [comment]
Can you post a screenshot of your browser's console and network tab (including all requests) by chance?

**Comment by moabi** [comment]
Ok, got it (yesterday was off, sorry for the delay), I set up a 4 char passwords with the cli, and it's not accepted on the gui, I guess I'll need to reset it

**Comment by brandonkelly** [comment]
Huh, interesting, which CLI action did you set it with? `install`?

**Comment by moabi** [comment]
Yes exactly

**Comment by brandonkelly** [comment]
Yep, able to reproduce, apparently we’re not validating the password length there. Will fix…
