### ISSUE TITLE
Link to Commerce example templates in the docs is wrong

### ISSUE THREAD

**Issue by bleepsandblops** [craftcms/docs#39]
### Description
On this page
https://craftcms.com/docs/commerce/3.x/example-templates.html
the first link at the top
https://github.com/craftcms/commerce/tree/master/templates
is a 404

It should instead be
https://github.com/craftcms/commerce/tree/master/example-templates

**Comment by mattstein** [comment]
Just updated, thanks @bleepsandblops!
