### ISSUE TITLE
Improve “How to Build a Module”

### ISSUE THREAD

**Issue by luke-nehemedia** [craftcms/docs#396]
I have a suggestion for https://craftcms.com/docs/4.x/extend/module-guide.html

There are some mistakes here. Sometimes the namespace (bar) and plugin-id (foo) are mixed up I think. 

For example, the `composer.json` entry should be:
```
{
  // ...
  "autoload": {
    "psr-4": {
      "bar\\": "modules/bar/"
    }
  }
}
```

with the plugin in `modules/bar/foo`.

Then, the `config/app.php` should be
```
return [
    // ...
    'modules' => [
        'foo' => bar\foo\Module::class,
    ],
    'bootstrap' => [
        'foo',
    ],
];
```

**Comment by brandonkelly** [comment]
I think it was actualy correct (it suggested creating a `modules/foo/` folder to contain the module), it was pretty confusing. I’ve just swapped over to using `foo` everywhere.
