### ISSUE TITLE
[4.x]: Site URL is set to the directory name, not what's entered during `composer create`

### ISSUE THREAD

**Issue by olets** [craftcms/docs#397]
### Description

When as documented in the tutorial https://craftcms.com/docs/getting-started-tutorial/install/ with the exception of using a custom name for the directory I was installing Craft in, the resulting site came out with the Site Url `https://<my directory>.ddev.site` not `https://tutorial.ddev.site`.

### Steps to reproduce

```shell
% mkdir craft-tutorial # differs from the tutorial instructions, which use `tutorial`
% cd craft-tutorial
% ddev config --project-type=php --php-version=8.0
% ddev composer create -y craftcms/craft
# snip
Site URL: https://tutorial.ddev.site
# snip
% ddev config --docroot=web
% ddev start
```

### Expected behavior

```shell
# snip
Successfully started craft-tutorial
Project can be reached at https://tutorial.ddev.site https://127.0.0.1:63681
```

### Actual behavior

```shell
# snip
Successfully started craft-tutorial
Project can be reached at https://craft-tutorial.ddev.site https://127.0.0.1:63681
```

### Craft CMS version

4.1.4.1

### PHP version

8.0.21

### Operating system and version

macOS 12.4

### Database type and version

MySQL 10.3.35

### Image driver and version

Imagick 3.6.0 (ImageMagick 6.9.11-60)

**Comment by brandonkelly** [comment]
If you specify any args to `ddev config` such as `--project-type` and `--php-version`, the command will be run non-interactively and assume the defaults for any other values. In the case of the project name, that will be the name of the directory.

I’ve just added a `--project-name=tutorial` arg to the suggested command, which should prevent anyone else from running into this if they happened to use a different project folder name.

In your case, you can either run the following command:

```sh
ddev config --project-name=tutorial
```

or open `.ddev/config.yaml` and change the `name` property at the top to `tutorial`.

Then run the following:

```sh
ddev restart
```
