### ISSUE TITLE
Signal 11 on install

### ISSUE THREAD

**Issue by chadwilken** [craftcms/docs#40]
I am attempting to setup Craft 3 and am receiving the following error when I try to install:
![error](https://i.imgur.com/EHuNpuQ.png)

Not sure what I am doing incorrectly. I normally do not work in PHP, but the marketing team needs this setup.
I am running: PHP 7.1.7 Zend Engine v3.1.0 with Composer 1.5.2

**Comment by brandonkelly** [comment]
Signal 11! 😱

Can you check to see if you have any log files in `storage/logs/` ? if so, can you paste the contents in here?

**Comment by chadwilken** [comment]
@brandonkelly thanks for the quick reply. Unfortunately, there aren't any logs. Is there a way to run this in verbose mode?

**Comment by chadwilken** [comment]
Well if I run composer with the -v option I get:
```
                                                          
  [Symfony\Component\Process\Exception\RuntimeException]  
  The process has been signaled with signal "11".         
                                                          

Exception trace:
 () at phar:///usr/local/bin/composer/vendor/symfony/process/Process.php:370
 Symfony\Component\Process\Process->wait() at phar:///usr/local/bin/composer/vendor/symfony/process/Process.php:202
 Symfony\Component\Process\Process->run() at phar:///usr/local/bin/composer/src/Composer/Util/ProcessExecutor.php:68
 Composer\Util\ProcessExecutor->execute() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:235
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:96
 Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php:237
 Composer\Command\CreateProjectCommand->installProject() at phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php:143
 Composer\Command\CreateProjectCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:266
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:861
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:208
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:245
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:127
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:100
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:54
 require() at /usr/local/bin/composer:24
```

**Comment by takobell** [comment]
Maybe a bug in the version of PHP you're running? https://github.com/symfony/symfony/issues/20988

https://bugs.php.net/bug.php?id=73989

**Comment by brandonkelly** [comment]
A couple other people are seeing this with Beta 31. Looking into it…

For the meantime, you can grab Beta 30 like this:

```
> cd path/to/craft3/project
> composer require craftcms/cms:"3.0.0-beta.30"
```

Then re-run the setup stuff by running:

```
> ./craft setup
```

**Comment by c4milo** [comment]
@brandonkelly apologies for my ignorance, I'm new to PHP. When I try to pin the version, I get this error: 

![](https://cldup.com/tMNtP2SawF.png)

**Comment by brandonkelly** [comment]
@c4milo Give us a few, we’ve been able to reproduce the issue and are fixing it…

**Comment by brandonkelly** [comment]
Alright. Beta 32 is out with a fix for that segfault error. Since this is a fresh Craft3 project, maybe just delete your project folder and re-install.

Sorry for the inconvenience!

**Comment by c4milo** [comment]
Thanks for the extremely quick fix @brandonkelly!

**Comment by chadwilken** [comment]
That did the trick, cheers!
