### ISSUE TITLE
The General Config Settings documentation doesn't mention the "fluent" syntax

### ISSUE THREAD

**Issue by simonkuran** [craftcms/docs#403]
### Description
Since a fresh install of Craft now generates a general.php file with the fluent setter methods [the docs](https://craftcms.com/docs/4.x/config/config-settings.html) should document how they work, especially for more complex options like arrays for aliases.

### Additional info

- Craft version: 4.2.0.2
- PHP version: 8.1

**Comment by AugustMiller** [comment]
Thanks for the nudge! Still playing catch-up with a few 4.x features, so this is top-of mind.

💡 For anyone looking for some information in the interim, I strongly recommend reviewing [Fluent Multi-Environment Config](https://nystudio107.com/blog/fluent-multi-environment-config-for-craft-cms-4) by Andrew Welch, the original feature contributor!

**Comment by AugustMiller** [comment]
Just merged #411, which includes [a new section](https://craftcms.com/docs/4.x/config/#style-map-vs-fluent) describing the fluent config system.
