### ISSUE TITLE
Explain how to interact with controller actions via AJAX

### ISSUE THREAD

**Issue by nfourtythree** [craftcms/docs#413]
### Description
Since standardising (in Craft and Commerce 4) the return of success and failures in controller actions it would be handy to have a helpful hint on best practices and what to expect when submitting data and what is returned.

### Related Issues
https://github.com/craftcms/commerce/issues/2933

**Comment by AugustMiller** [comment]
Hey! Snuck this in as part of #428: https://craftcms.com/docs/4.x/dev/controller-actions.html#ajax
