### ISSUE TITLE
Improve “Template Roots”

### ISSUE THREAD

**Issue by hypeJunction** [craftcms/docs#418]
I have a suggestion for https://craftcms.com/docs/4.x/extend/template-roots.html:

It doesn't work

**Comment by hypeJunction** [comment]
After fighting with it for a bit, it turned out that the `bootstrap` for custom module wasn't enabled in `app/config.php` even though the module was present in the filesystem (default `composer create-project`)

**Comment by AugustMiller** [comment]
Glad you found your solution!

For anyone else finding this in the future, see the [docblock in the base module class](https://github.com/craftcms/craft/blob/main/modules/Module.php#L15-L18) for the `bootstrap` instructions @hypeJunction is talking about.
