### ISSUE TITLE
[Feature Request] add dark/light mode toggle

### ISSUE THREAD

**Issue by mattstein** [craftcms/docs#44]
### Description

Right now the theme honors your browser/system setting for `prefers-color-scheme`, but it’d be nice to allow the visitor to optionally override that with an on-page control.

**Comment by cscomfort** [comment]
Working at a university, we're keen on accessibility and the dark mode introduced heaps of WCAG contrast failures -- and as we try to bring Craft on board for more of our projects, we need to feel confident that we can refer our users to the documentation.

It would be nice if the docs defaulted to the original light theme, with the option -- as suggested by @mattstein -- to toggle to dark.

Keep up the great work!

**Comment by mattstein** [comment]
Thanks @cscomfort! I think it’s important to continue honoring the visitor’s browser/OS setting by default, adding the ability to explicitly override if they’d prefer. Improving contrast and accessibility is a separate issue that’s definitely in the queue.

**Comment by mattstein** [comment]
Just merged this in!
