### ISSUE TITLE
Image Transforms: Missing AVIF option

### ISSUE THREAD

**Issue by rogerdawkins** [craftcms/docs#448]
### Description

The option to use **avif** as image format in image transforms is missing in the docs.

https://craftcms.com/docs/4.x/image-transforms.html

Two references:
- Defining Transforms from the Control Panel > Image Format options
- Defining Transforms in your Templates > Possible Values
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by AugustMiller** [comment]
Thanks! Added AVIF and WEBP, noting that they are only supported by ImageMagick.
