### ISSUE TITLE
Incorrect links on the Field Layouts block

### ISSUE THREAD

**Issue by iliaivanov** [craftcms/docs#45]
Just a minor issue with one link on the fields page: https://github.com/craftcms/docs/blob/master/en/fields.md#field-layouts

`Categories use the field layout defined by their Category Group in Settings → Categories → [Category Group name] → Field Layout.` - Categories link is pointing to the `https://github.com/craftcms/docs/blob/master/en/categories` but missing _.md_ at the end.

The same thing is for _Tags_ and _Users_.

**Comment by brandonkelly** [comment]
Thanks for pointing that out!
