### ISSUE TITLE
RelatedTo - use proper syntax for "and" relations.

### ISSUE THREAD

**Issue by piotrpog** [craftcms/docs#47]
https://craftcms.com/docs/3.x/relations.html#simple-relationships

Here's how `and` usage is described in code example:

```
{% set relatedDrinks = craft.entries()
    .section('drinks')
    .relatedTo([ 'and', gin, lime ])
    .all() %}
```

It turns out however that in order for it to work correctly, such syntax needs to be used - at least with php:

```
$query->relatedTo(['and', ['element' => gin], ['element' => lime]])
```

Using syntax below in php, causes `array_merge(): Argument #2 is not an array` error:

```
$query->relatedTo(['and', gin, lime])
```

**Comment by mattstein** [comment]
Hey @piotrpog, I’m not sure I’m following. Those examples use proper syntax for the templating section they’re in—are you suggesting that we add PHP examples to the page as well or describing a problem with the Twig examples that exist now?
