### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ArnyS** [craftcms/docs#47]
Generating optimized autoload files
Generating optimized autoload files
> @php craft setup/welcome

Parse error: parse error in /vh/inesco.dev/craft/vendor/craftcms/cms/bootstrap/bootstrap.php on line 104
Script @php craft setup/welcome handling the post-create-project-cmd event returned with error code 255

**Comment by takobell** [comment]
That error indicates that your PHP version isn't 7+, which Craft 3 requires. https://github.com/craftcms/docs/blob/master/en/requirements.md#server-requirements-1
