### ISSUE TITLE
Small syntax-error in docs hides pageTrigger-documentation

### ISSUE THREAD

**Issue by alexgit2k** [craftcms/docs#470]
Commit 179171c  inserted backticks before the tip which renders the `pageTrigger`-documention below `omitScriptNameInUrls` as code instead of Markdown: https://craftcms.com/docs/4.x/config/general.html#omitscriptnameinurls

**Comment by AugustMiller** [comment]
Ahhh, good catch. Issued PR craftcms/cms#12659.

**Comment by AugustMiller** [comment]
Resolved! Thanks for the report.
