### ISSUE TITLE
Tutorial’s “Front End Options” lack context

### ISSUE THREAD

**Issue by TheS0upDrag0n** [craftcms/docs#486]
I have a suggestion for https://craftcms.com/docs/getting-started-tutorial/build/:
Please could you explain what "front end presentation", "Twig templtes" and "headless" mean? This intro is not meant to assume you know all this already.

**Comment by AugustMiller** [comment]
Agreed—I have a [branch](https://github.com/craftcms/docs/pull/487) tracking an overhaul of the _Getting Started_ tutorial that (among other things) seeks to explain these choices in greater detail!

Looking forward to wrapping up those changes this week and next.

**Comment by TheS0upDrag0n** [comment]
Thank you
