### ISSUE TITLE
Console commands contain --isolated without explanation

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/docs#488]
### Description

Right now, all console commands have this string at the end:

> --isolated :

This doesn't look intentional? It's not formatted as code, there's the space before the colon and the explanation is lacking. Shouldn't this be documented as a global option since all commands have it? Maybe some find/replace gone wrong?

![Screenshot 2023-03-29 at 16 59 34](https://user-images.githubusercontent.com/10146880/228581551-2e30f6b0-550c-46a0-93d2-f7414d9e4158.png)
![Screenshot 2023-03-29 at 16 59 38](https://user-images.githubusercontent.com/10146880/228581557-7e2490b8-a02f-4ffb-9572-ed492d0a8223.png)

---

Maybe this should be a separate issue, but I also noticed that the global parameters like `--interactive` and `--isolated` aren't really documented anywhere, maybe they should be mentioned above the list of commands?

**Comment by AugustMiller** [comment]
Thanks for the report! I think I've gotten this bug ironed out.

I also took the opportunity to add a new [Global Options](https://craftcms.com/docs/4.x/console-commands.html#global-options) section before the comprehensive list of commands.

**Comment by MoritzLost** [comment]
@AugustMiller Thanks, the global options documentation is great!
