### ISSUE TITLE
[4.x]: Event Code Generator not working?

### ISSUE THREAD

**Issue by freder** [craftcms/docs#489]
### What happened?

v3:
<img width="992" alt="Screenshot 2023-03-30 at 12 33 39" src="https://user-images.githubusercontent.com/724844/228810690-6209184a-c689-4b42-bf78-c1465c803003.png">

v4:
<img width="994" alt="Screenshot 2023-03-30 at 12 34 08" src="https://user-images.githubusercontent.com/724844/228810727-dc11d8e4-faaf-4797-8edf-da4e414df6ee.png">

### Craft CMS version

4.x

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
I’m not sure why it was saying “0 items” at the time. It currently shows 
`3,751 items` for me though:

<img width="707" alt="Screenshot of the event search input, with a “3,751 items” label above it." src="https://user-images.githubusercontent.com/47792/229386402-04711bfd-ae94-4acf-8af2-4f6b6a73827d.png">

We’ll keep an eye on it.

**Comment by brandonkelly** [comment]
Thanks for pointing that out! The page is listing events now: https://craftcms.com/docs/commerce/4.x/extend/events.html
