### ISSUE TITLE
Migrate structure and settings without content

### ISSUE THREAD

**Issue by ChrisButterworth** [craftcms/docs#49]
Content migrations are brilliant if not a little confusing but wondered if there is a way to migrate settings and structure without migrating all the content.

This would massively help when there are dev, staging and production environments running and structures need to be migrated between them when its a larger project with multiple phases.

**Comment by brandonkelly** [comment]
Content migrations are really just PHP scripts that you can do whatever you want from. So yes, possible to migrate just structure-y things without content.

**Comment by ChrisButterworth** [comment]
Any guidance on how?? With the incomplete docs it makes it a bit more difficult.

**Comment by brandonkelly** [comment]
Yeah sorry realize the docs are lacking right now. You pretty much need to learn plugin development to get anything done with content migrations right now. We plan on making it easier (and providing documentation) down the road.

You can see some examples here: https://github.com/pixelandtonic/craftcom/tree/develop/migrations (albeit these are for building  application-specific DB schema, more than migrating content around).
