### ISSUE TITLE
[Content]: Installation Instructions (Non-DDEV)

### ISSUE THREAD

**Issue by cherrykoda** [craftcms/docs#555]
### Product

Craft CMS

### Description

The Craft docs should include a non-DDEV installation instructions for setting up Craft. I personally dont need it, but Ive known new to Craft devs who want to set things up on their other dev tools. 

Quicksetup as DDEV makes sense, I just think there should be the other set of setup instructions too.
(without having to parse the DDEV instructions for necessary bits)

From Discord Chat:
<img width="1130" alt="image" src="https://github.com/craftcms/docs/assets/3789834/1a743524-8bda-4a36-8800-9a01d026afc8">

**Comment by AugustMiller** [comment]
This has come up a few times in Discord (and the official support inbox)! I figured I would capture some thoughts on this, in case anyone ends up seeking out rationale for our focus on DDEV. This is something we're thinking about all the time, but believe the community _and_ product stack are best served by the current emphasis on containerized development environments.

The shift in focus to DDEV was in response to two main factors:

- The community’s rapid adoption: we actually lagged significantly—until late last year, the bulk of setup still revolved around things that were antithetical to a productive first-encounter with Craft, like file permissions and Apache or nginx configuration!
- Support throughput: being able to screen issues that stem from improperly configured local development environments by standardizing the stack has made it possible for Tommy, Oli, and Brad to reach and support _far_ more Craft users—and for the CMS + Commerce teams to replicate, identify, and patch bugs significantly faster.

---

We do interject above the quick-start instructions that they are DDEV-specific, and mention that other options are available:

![Screen Shot 2023-12-15 at 10 48 02](https://github.com/craftcms/docs/assets/1895522/bbfc9780-3ad0-4b35-bdb4-116f8bbcafd2)

That section links down to a list of [alternate installation methods](https://craftcms.com/docs/4.x/installation.html#alternative-installation-methods), including a KB article that has generic instructions that will work across a number of tools. I've updated the intro of that article to make note of the tool-specific tips at the end:

![Screen Shot 2023-12-15 at 10 50 31](https://github.com/craftcms/docs/assets/1895522/e3f22b84-c297-41b8-be88-ece0d6b4f34e)

There, we discuss the MAMP family of products, Docker, Valet, and Homestead.

---

Asides:

- The Tailwind example is _awesome_, but part of a different world—they are describing integrations for _code_, not infrastructure. Our goal is to get a developer set up with an environment that is capable of interpreting PHP, serving HTTP requests, accessing a database, etc… which I would argue is more akin to figuring out how you want to run Node, or even something closer to home, like [Laravel](https://laravel.com/docs/10.x#creating-a-laravel-project).
- One super cool development feature that we don't advertise enough is `php craft serve` (even if it only solves the PHP + HTTP components of the environment)!
