### ISSUE TITLE
Dollar sign in database password botches command line install

### ISSUE THREAD

**Issue by chrissam42** [craftcms/docs#56]
I used the command-line install method and used a database password with a dollar sign in it. It appears that it got interpreted as a shell variable as the resulting password in `.env` was missing the dollar sign and character after it (which was a number).

**Comment by brandonkelly** [comment]
@chrissam42 Can you provide details about the environment (OS & version, PHP version)?

(FFR this should have been posted to the [craftcms/cms](https://github.com/craftcms/cms) repo.)

**Comment by chrissam42** [comment]
Oh sorry, I can repost there with more details if you like.

**Comment by chrissam42** [comment]
On trying to replicate this with a new test install, it is working fine, so I must have been asleep at the switch yesterday. Sorry to bother you.

**Comment by brandonkelly** [comment]
hah, no worries!
