### ISSUE TITLE
[Bug]: Query parameters missing from page

### ISSUE THREAD

**Issue by sparkalow** [craftcms/docs#573]
### Page URL

https://craftcms.com/docs/3.x/categories.html#parameters

### Client

OSX, Firefox latest

### Details

The query parameters for category elements appear to be missing on craft 3 docs page.

### Steps to reproduce

1. visit https://craftcms.com/docs/3.x/categories.html#parameters
2. Attempt to read about category query parameters.

**Comment by AugustMiller** [comment]
Thanks for reporting. I've added the proper `include` block that ought to have been there after #552!
