### ISSUE TITLE
[Content]: Updating plugins document refers to Craft 4 instead of Craft 5

### ISSUE THREAD

**Issue by pixelmachine** [craftcms/docs#578]
### Product

Craft CMS

### Description

In several places the document refers to Craft 4 where it should refer to Craft 5. Additionally it's slightly confused but the fact that there are also details about upgrading from Craft 3 plugins.

**Comment by AugustMiller** [comment]
I suspect you’re talking about [this page](https://craftcms.com/docs/5.x/extend/updating-plugins.html)?

We are still working through the required changes to 5.x documentation, so there are bound to be a lot of pages that still have the 4.x content on them!

**Comment by pixelmachine** [comment]
Yep that's the one, sorry thought I added the link.

All good then if you're still working on it!
