### ISSUE TITLE
[Bug]: Links to craft fields missing slash - broken link

### ISSUE THREAD

**Issue by leevigraham** [craftcms/docs#588]
### Page URL

https://craftcms.com/docs/5.x/extend/field-types.html

This line:  https://github.com/craftcms/docs/blob/c2b3641a8d6306821f8ddb1f0296500e1698fcbc/docs/5.x/extend/field-types.md?plain=1#L94

Creates this url: `https://github.com/craftcms/cmsblob/5.x/src/fields/Date.php` which should be `https://github.com/craftcms/cms/blob/5.x/src/fields/Date.php`

**Comment by AugustMiller** [comment]
Thanks for reporting—should be fixed, now!
