### ISSUE TITLE
Please change the highlight colour to be visible

### ISSUE THREAD

**Issue by darylknight** [craftcms/docs#59]
Love the new dark mode docs, but I can't see whether I've selected anything from the code examples. Could you please update that to something visible?

Example of text not selected:

![image](https://user-images.githubusercontent.com/1250017/90519467-b8b9ea00-e170-11ea-8230-8339d11866d5.png)

Example of a highlighted selection:
![image](https://user-images.githubusercontent.com/1250017/90519486-bf486180-e170-11ea-9e60-6c1ebdc7b60e.png)

Probably depends on the monitor settings slightly, but I can't see it at all on at least two of my screens, which makes it very difficult to select and copy code / variables. Thanks!

**Comment by mattstein** [comment]
You’re right @darylknight, that was borderline cruel. Thanks for calling that out!

**Comment by darylknight** [comment]
Sweet, thanks Matt!
