### ISSUE TITLE
Clarification on deprecation

### ISSUE THREAD

**Issue by andrewfairlie** [craftcms/docs#60]
In https://github.com/craftcms/docs/blob/master/en/changes-in-craft-3.md#template-tags

> The following Twig template tags have been deprecated, and will be removed in Craft 4:

Does this mean...

1. They've been renamed in Craft 3, and will be removed altogether in Craft 4
2. They've been renamed in Craft 3, but the old tags will still work until Craft 4

Sorry, not quite sure which one is the intention and planning how we write templates going forward.

**Comment by brandonkelly** [comment]
The second one. You should still update your templates ASAP, but we wanted to make Craft 2 sites _loadable_ in Craft 3 with as little effort as possible. It’s more fun fixing deprecation errors on a working site than fixing endless breaking errors and not being sure when you’ll fix the one that gets your page to finally load.
