### ISSUE TITLE
Events missing from Craft 3 documentation

### ISSUE THREAD

**Issue by dmatthams** [craftcms/docs#60]
Not sure if it's hidden somewhere, but it exists on Craft 2 and Craft Commerce 3.

Just looking for a list of events that plugins/modules can use.

Thanks!

**Comment by mattstein** [comment]
You’re not wrong @dmatthams, thanks for the issue. We’re working on standardizing and improving event documentation for Craft and Commerce, part of which will include conveying when events are triggered across common scenarios. I’ll leave this open until that’s a reality!

**Comment by mattstein** [comment]
Just launched a new Events page here: https://craftcms.com/docs/3.x/extend/events.html
