### ISSUE TITLE
[Broken Link]: Changelog link in Craft 5 Upgrade page leads to 404 on github

### ISSUE THREAD

**Issue by matthisamoto** [craftcms/docs#600]
### URL

https://github.com/craftcms/cms/blob/main/CHANGELOG.md

### Additional Details

in [Breaking Changes and Deprecations section of Upgrading from Craft 4 page](https://craftcms.com/docs/5.x/upgrade.html#breaking-changes-and-deprecations) there's a link in the box  saying:

```
This list focuses on high-traffic, user-facing features. Review the complete 
changelog for information about changes to specific APIs, including class
deprecations, method signatures, and so on.
```

[The link](https://github.com/craftcms/cms/blob/main/CHANGELOG.md) resolves to a 404 on github as of now.

**Comment by AugustMiller** [comment]
Thanks for reporting—fixed!
