### ISSUE TITLE
Incorrect Link in 4.x Money Fields Documentation

### ISSUE THREAD

**Issue by kragit** [craftcms/docs#609]
### URL

https://craftcms.com/docs/4.x/money-fields.html

### Additional Details

The 4.x page for Money Fields displays the depreciation notice and directs you to the new page, though it appears this is linking to the 5.x Matrix Field page, not the money field page.

Current link: `https://craftcms.com/docs/5.x/reference/field-types/matrix.html`

Likely intended link: `https://craftcms.com/docs/5.x/reference/field-types/money.html`

![Snapshot_2024-05-21_12-56-42](https://github.com/craftcms/docs/assets/296050/556ec4d2-ccb3-4f81-bb39-c887bb3e5205)

Additionally, it appears the [Querying Elements](https://craftcms.com/docs/5.x/reference/field-types/money.html#querying-elements-with-money-fields) section references the Date field, when I believe it should say Money field.

`When [querying for elements](https://craftcms.com/docs/5.x/development/element-queries.html) that have a **Date** field, you can filter the results based on the Money field data using a query param named after your field’s handle.`

**Comment by AugustMiller** [comment]
Oop! Fixed in 116a34cbc70e6810e2c4bc77b0df06a71c1dee84 and d9f1ee04ddc8c73f7be2922aeda9aede50a87cf8.
