### ISSUE TITLE
Better explanation or example for using aliases in regards to setting URL.

### ISSUE THREAD

**Issue by Chrisedmo** [craftcms/docs#61]
Hi - I am working in a Craft 3 site and looking to push it live soon, but I wanted to know how the new Alias works, and specifically how it will work when doing things like :

```
    // Dev environment settings
    'dev' => [
        // Base site URL
        'siteUrl' => 'http://craft3test.dev',
        'devMode' => true,
    ],
```

**Comment by brandonkelly** [comment]
Here you go: https://github.com/craftcms/docs/blob/master/en/configuration.md#aliases

**Comment by magnessjo** [comment]
The URL posted is missing the version number.  If you are looking for this information in the future, you can just walk into the main project :  https://github.com/craftcms/docs.  

For today: the link is (note the v3): 
  https://github.com/craftcms/docs/blob/v3/en/configuration.md#aliases

**Comment by brandonkelly** [comment]
@magnessjo thanks! updated the original URL too.
