### ISSUE TITLE
[5.x]: Stores - location in twig

### ISSUE THREAD

**Issue by bartdigitalpulse** [craftcms/docs#611]
### Product

Commerce

### Description

https://craftcms.com/docs/commerce/5.x/system/stores.html#location

The example code:
`{{ store.settings.address|address }}`
Should probably be 
`{{ store.settings.locationAddress|address }}`

store.settings doesn't have an address property.

**Comment by AugustMiller** [comment]
Yep, right you are! Fixed in 7d9fe71.
