### ISSUE TITLE
[Content]: docs for v5 still mention Field Groups

### ISSUE THREAD

**Issue by i-just** [craftcms/docs#622]
### Product

Craft CMS

### Description

v5 docs for Custom Fields mention Field Groups: https://craftcms.com/docs/5.x/system/fields.html, but those were dropped in Craft 5 (both copy and screenshot need updating).

(Related issue: https://github.com/craftcms/cms/issues/15191)

In case it helps, here’s an explanation as to why they were dropped: https://github.com/craftcms/cms/discussions/14083

**Comment by AugustMiller** [comment]
Fixed this somewhere along the line…! 😅
