### ISSUE TITLE
Dashboard  Twig Runtime Error – Twig_Error_Runtime

### ISSUE THREAD

**Issue by pierreluckffein** [craftcms/docs#63]
It seems that I am able to create a field called "author" and saving an entry with this field creates an error on the dashboard for the recent entry tabs. it's trying to access the author object, but it gets the custom author field.

> Impossible to access an attribute ("username") on a string

`{%- if CraftEdition >= CraftClient and entry. author %}, {{ entry.author.username}} {% endif -%}` line 10 in vendor/craftcms/cms/src/templates/_components/widgets/Recent Entries/body.html

Shouldn't "author" be a restricted handle ?

**Comment by brandonkelly** [comment]
> Shouldn't "author" be a restricted handle ?

A field called `author` would work totally fine on anything besides entries, and there are legitimate use cases where it would be desired (e.g. storing the author of photos in an asset volume).

That said, we do want to improve this down the road with craftcms/cms#1524.

(FFR please post Craft CMS issues to the [craftcms/cms](https://github.com/craftcms/cms) repo – thanks!)
