### ISSUE TITLE
Broken link to "updating" under deploy documentation

### ISSUE THREAD

**Issue by kbergha** [craftcms/docs#632]
### URL

https://craftcms.com/docs/5.x/updating.html

### Additional Details

On this page: https://craftcms.com/docs/5.x/deploy.html
There is a link under the heading "System Updates + Project Config" that leads to to URL given in this report:

`Craft uses Composer under the hood to install and [update](https://craftcms.com/docs/5.x/updating.html) plugins and packages it depends on.`

Should link to https://craftcms.com/docs/5.x/update.html ??

**Comment by AugustMiller** [comment]
Must have fixed this at some point… thanks for the report! 😅
