### ISSUE TITLE
Composer create-project is killed

### ISSUE THREAD

**Issue by speder** [craftcms/docs#64]
When following the directions [here](https://github.com/craftcms/docs/blob/v3/en/upgrade.md#if-you-want-your-directory-structure-to-resemble-a-new-craft-3-project)  to upgrade an existing Craft 2 app, the composer process is mysteriously "killed" after a few seconds, leaving no vendor/ directory created:

```
$ time composer create-project -s RC craftcms/craft app
Installing craftcms/craft (1.0.23)
  - Installing craftcms/craft (1.0.23): Loading from cache
Created project in app
> @php -r "file_exists('.env') || copy('.env.example', '.env');"
Loading composer repositories with package information
Updating dependencies (including require-dev)
Killed

real	0m6.023s
user	0m3.276s
sys	0m0.396s
$  ls -1 app/
composer.json
config
craft
craft.bat
LICENSE.md
modules
README.md
storage
templates
web
$ composer -v|grep 'Composer version'
Composer version 1.6.2 2018-01-05 15:28:41
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
$ 

```

* No additional info is provided by composer.
* Nothing in any log I can find.
* /server/checkit.php checks out.

**Comment by brandonkelly** [comment]
Similar issue here: https://github.com/composer/composer/issues/1815 - try reading through the solutions in the comments.

**Comment by speder** [comment]
Thanks Brandon, it was indeed oom-related and easily solved by adding some swap memory.

**Comment by John-doe-lee** [comment]
`localhost:~/drupal# cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.7.0
PRETTY_NAME="Alpine Linux v3.7"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"`

`localhost:~/drupal# composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Killed
`
how to solve it?

**Comment by speder** [comment]
@John-doe-lee Adding swap memory fixed it for me, as shown, eg [here](https://github.com/composer/composer/issues/1815#issuecomment-244376380)
