### ISSUE TITLE
Outdated example in Docs

### ISSUE THREAD

**Issue by Visiluna** [craftcms/docs#649]
### Description

https://craftcms.com/docs/5.x/reference/twig/filters.html#without

The Craft 5 docs for the `|without` filter includes the following code sample:

`{% set entries = craft.entries().section('articles').limit(3).find %}`

Pretty sure `.find` had been deprecated for a while.

**Comment by AugustMiller** [comment]
Fixed in 3c8af6f316edcb8f3684c304b8468753e9eb79fa. Thank you! 💞
