### ISSUE TITLE
Improve “Entries”

### ISSUE THREAD

**Issue by architchandra** [craftcms/docs#65]
I have a suggestion for https://craftcms.com/docs/3.x/entries.html

The feedback is actually for the overall documentation site. It would be great if the search bar can be _fixed_ at the top so that even if I am reading something near the bottom of the page, I can press `/` and search the site from there.

**Comment by mattstein** [comment]
Thanks for the suggestion, @architchandra. We considered keeping search fixed like in the [class reference](https://docs.craftcms.com/api/v3) but decided to give priority to page content instead. You *should*, however, be able to press `/` at any time to focus on the search field regardless of your scroll position.
