### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by hatyi** [craftcms/docs#650]
### URL

https://craftcms.com/docs/commerce/5.x/system/extend/events.html

### Additional Details

FYKI 
On [this page](https://craftcms.com/docs/commerce/5.x/system/products-variants.html#variant-stock) if you click the link behind the text "the orderStatusChange event " it results in a 404.
[This is the link](https://craftcms.com/docs/commerce/5.x/system/extend/events.html#orderstatuschange) that is throwing it.

**Comment by AugustMiller** [comment]
Sorry, I can't seem to find the link you're describing! Feel free to reopen or `@` me if you hit it again.

**Comment by hatyi** [comment]
> Sorry, I can't seem to find the link you're describing! Feel free to reopen or `@` me if you hit it again.

Yeah seems like it was fixed here

docs/.artifacts/commerce/5.x/products-variants.md
https://github.com/craftcms/docs/commit/b9502b3c12d682bb1428efe5202dbffb8dd3a66f#diff-f4ba1b7bad4d092b3c8bb764de53ea5b97d91ff490c9a2ff18f10fc031dbf097L1491

![Image](https://github.com/user-attachments/assets/99a91a68-9453-4c85-86fc-3ada50677b82)


Probably was just not merged yet when I reported it.
Cheers!
