### ISSUE TITLE
[Content]: Knowledge Base - incorrect function name getTypeByHandle

### ISSUE THREAD

**Issue by BitBy73Bit** [craftcms/docs#657]
### Product

Craft CMS

### Description

Within the example code provided on the [Entry Form](https://craftcms.com/knowledge-base/entry-form) knowledge base article, there are multiple references to the function `craft.app.entries.getTypeByHandle()`, however I believe this should actually state `craft.app.entries.getEntryTypeByHandle()` as per the [class reference docs](https://docs.craftcms.com/api/v5/craft-services-entries.html#method-getentrytypebyhandle)

Apologies if this is the wrong repo, but I couldn't find a specific repo that covers the knowledge base content. If someone can signpost me, I'm happy to re-raise in the appropriate place.

**Comment by AugustMiller** [comment]
Fixed! Thanks for the heads up. 💞
