### ISSUE TITLE
[5.x] vs [4.x:] [Docs] Eager loading documentation differences

### ISSUE THREAD

**Issue by rob-c-baker** [craftcms/docs#661]
### Description

When you look at this (v4): https://craftcms.com/docs/4.x/dev/eager-loading-elements.html

vs this (v5): https://craftcms.com/docs/5.x/development/eager-loading.html

The v4 docs talk about [elements related to matrix blocks](https://craftcms.com/docs/4.x/dev/eager-loading-elements.html#eager-loading-elements-related-to-matrix-blocks) and use an example like this:

```twig
{% set entries = craft.entries()
  .section('news')
  .with(['matrixField.blockType:assetsField'])
  .all() %}
```

Note the use of `:`.

When picking through the source code of v5 it looks like this, or something like it is still in the source code but not mentioned anywhere in the v5 docs. I know matrix block types are gone in favour of entry types but it's not clear:

- If this syntax should still work
- If it does, I am assuming the entry type handle would go where above currently has `blockType`?

I'm also assuming that the field handles in `with()` definitions should be the field handles on the entry type and not the field handles they "extend" from on the global fields themselves (i.e. with the numbers appended - see below). Is that correct?

#### Context

I am working with an upgraded (not deployed yet) site where there are a large number of entry types and fields that have had numbers appended to their field handles.

It is pretty tricky working out what handles, with what particular number appended go in which spots with the eager loading definitions. Once I can get performance up to a good enough standard with the fields like this, I'm planning to do probably several passes of field merging but that cannot happen until I get the release out.

**Comment by rob-c-baker** [comment]
Sorry, this should have been posted here: https://github.com/craftcms/docs/issues

**Comment by rob-c-baker** [comment]
There may be an actual bug here too, so in Craft 5.4.4, I have this eager loading map:

```twig
{% set eager_load_map = [
	[ 'navigation', { with: [
                [ 'topLevel' ],
		[ 'topLevel.detail:entry', { limit: 1 }],
		[ 'elements' ],
		[ 'elements.heading3:entry', { limit: 1 }],
		[ 'elements.link:entry', { limit: 1 }],
	]}]
] %}
{# example follow on call #}
[entryQuery].with(eager_load_map).all()
```

`navigation` is an Matrix field in an Entry type on a section dedicated to being the site's main navigation
`navigation.topLevel` is a Matrix field holding a single block within `navigation`
`navigation.elements` is a Matrix field holding many blocks within `navigation`
The `entry` within the `topLevel` & `elements` Matrix blocks is an Entry Field that in each appearance holds a single entry representing the target of the navigation item.

Note that there are (at least) 2 different Entry types attached to the `elements` Matrix block but they all have an `entry` Entry Field.

The issue is that depending how you adjust the map (these bits: `navigation.elements:link.entry` & `navigation.elements:heading3.entry`) only 1 of them is ever actually eager loaded. I have tried many different iterations of how to lay this map out but they never **all** get eager loaded.

My guess here is that `navigation.elements:link.entry` & `navigation.elements:heading3.entry` are internally being treated as the same thing, effectively resolving to `navigation.elements.entry` but only ever applying to one the entry types on the Matrix block - it looks like the order they are defined in the map make no difference.

For reference, the same map, doing a working eager load on Craft 4 is this:

```twig
{% set eager_load_map = [
	[ 'navigation' ],
	[ 'navigation.topLevel' ],
	[ 'navigation.topLevel.entry', { limit: 1 } ],
	[ 'navigation.elements' ],
	[ 'navigation.elements.heading:entry', { limit: 1 } ],
	[ 'navigation.elements.link:entry', { limit: 1 } ]
] %}
```

Trying this on v5 doesn't work in the same way as the first snippet doesn't!

**Comment by brandonkelly** [comment]
Any time you eager-load a field on a nested entry within a Matrix field, you [need to prefix the filed handle with the entry type handle](https://craftcms.com/docs/4.x/dev/eager-loading-elements.html#eager-loading-elements-related-to-matrix-blocks). For example:

```twig
navigation.<handleA>:topLevel.<handleB>:entry
```

(Replace `<handleA>` with the entry type handle that contains the `topLevel` field; replace `<handleB>` with the entry type handle that contains the `entry` field.)

We removed the Matrix eager-loading examples from the Craft 5 docs because Craft 5 introduced [lazy eager-loading](https://craftcms.com/docs/5.x/development/eager-loading.html#lazy-eager-loading) which provides a far simpler syntax for eager-loading nested elements: just append `.eagerly()` to whatever nested element queries should be eager-loaded, before `.all()`/`.collect()`. No need to specify the `with` param anymore.
