### ISSUE TITLE
[Content]: Incomplete text on purchasable docs for 5.x

### ISSUE THREAD

**Issue by jlawrence-yellostudio** [craftcms/docs#663]
### Product

Commerce

### Description

[https://craftcms.com/docs/commerce/5.x/system/purchasables.html](url)

Text cut off, it just says "Purchasables themselves"

**Comment by AugustMiller** [comment]
Yikes, yeah! Turns out there was an incomplete sentence _and_ a Vue component that swallowed the rest of the page! 😭 Fixed in 38361a0679c5c59e6c2b92556681955d971e4e62.
