### ISSUE TITLE
[Content]: Supported versions still lists Craft 3, should it?

### ISSUE THREAD

**Issue by frank-laemmer** [craftcms/docs#666]
### Product

Other/Multiple/Not Sure

### Description

I don't think knowledge base content is here on GH, not sure where to best post. Craft 3 is listed as a support version (ending in April 2024), which is now in the past.

https://craftcms.com/knowledge-base/supported-versions#currently-supported-versions

Ideas

* Remove Craft CMS 3 from supported versions
* Create a new heading for versions that are not supported

**Comment by frank-laemmer** [comment]
![Image](https://github.com/user-attachments/assets/b7eb5830-9681-4c40-ac7d-dbcd5ee73909)

**Comment by AugustMiller** [comment]
Thanks for the feedback! I've split this into two tables for better readability. 💞
