### ISSUE TITLE
[Content]: Craft CMS 5 asyncCsrfInputs default value in the docs is wrong

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/docs#679]
### Product

Craft CMS 5 documentation

### Description

The `asyncCsrfInputs` config documentation says the value is default `false`. This is not correct per the codebase, it defaults to true.

![Image](https://github.com/user-attachments/assets/47de4dba-71cb-45e8-bcb7-19b070ead1ba)

https://craftcms.com/docs/5.x/reference/config/general.html#asynccsrfinputs

**Comment by jamesmacwhite** [comment]
This is potentially a bug with PHPStorm as it the default value isn't true, but PHPStorm flags true as the default value.

**Comment by jamesmacwhite** [comment]
![Image](https://github.com/user-attachments/assets/227c1bb9-2c8a-4e30-865f-a85c03931137)

**Comment by AugustMiller** [comment]
I think what we're seeing here is an odd side-effect of the fluent-style configuration—the default config value is indeed `false`, but the default _argument_ when calling `->asyncCsrfInputs()` is `true`.

This is similar to how element queries work: by default, queries don't return drafts or provisional drafts, but you can call `->savedDraftsOnly()` with no argument to apply query params required to return just saved drafts.

Hope this tracks! The only thing I can think that would improve clarity in the docs is reintroducing array-style config as the default tab for each example. Let me know if you have any theories!

**Comment by jamesmacwhite** [comment]
Thanks @AugustMiller. A case of confidently incorrect on my part. It does seem like a side effect of the fluent syntax. Noted for usage of fluent syntax in general config or queries.

Not sure if I can report anything upstream within PHPStorm, not sure if it coming from the IDE itself or EA inspections.

**Comment by AugustMiller** [comment]
Oh, to be clear—the inspections are definitely working correctly! `true` is the default value of the argument, but `false` is the initial value for that config property.

If you were to [use a closure](https://craftcms.com/docs/5.x/configure.html#style) to modify the config object, the difference might be easier to visualize:

```php
use craft\config\GeneralConfig;
use craft\helpers\App;

return function(GeneralConfig $config) {
    $config->asyncCsrfInputs = true;

    // ...

    return $config;
};
```

![Image](https://github.com/user-attachments/assets/83772c08-3db7-421b-a683-1ea20be998f5)

**Comment by jamesmacwhite** [comment]
Ah thanks @AugustMiller, it does make more sense! I'll note checking fluent config more closely going forward!
