### ISSUE TITLE
PR: Add @origin alias to compliment @web

### ISSUE THREAD

**Issue by timkelty** [craftcms/docs#72]
It would be nice to have an `@origin` alias with the `proto://host` (but without the path to index.php, like @web has.

Consider a subdir =-based multisite:

- `public/index.php`, `@web`: http://site.com
- `public/de/index.php` `@web`: http://site.com/de

For when we always want to reference our origin domain (e.g. if our assets were all hosted at root, we can't use `@web` because it also contains the path.

**Comment by brandonkelly** [comment]
Forgoing an alias and just using a root-relative path would also work here – only exception being if the URL needs to be shared (e.g. sent in an email).

**Comment by brandonkelly** [comment]
Can you post this to https://github.com/craftcms/cms/issues ?

**Comment by timkelty** [comment]
Derp - didn't know where I was, sorry :)
