### ISSUE TITLE
Improve “Dropdown Fields”

### ISSUE THREAD

**Issue by yfchen123** [craftcms/docs#84]
I have a suggestion for https://craftcms.com/docs/3.x/dropdown-fields.html, It is unclear about what the html part of the actual names of the object, does not work when I use it..... The entry part is especailly confusing....

**Comment by mattstein** [comment]
Thank you for the suggestion, @yfchen123.

Can you help me understand what part it is you find confusing? It would be helpful if you could share what you’re trying that does not work, or which parts of [the page](https://github.com/craftcms/docs/blob/main/docs/3.x/dropdown-fields.md) you’re referring to.

**Comment by yfchen123** [comment]
Hello mattstein: I used the code you suggested as below:
{% if row.hasSelect > 0 %}
                        <br>
                        <select name="{{ selectName }}" id="{{ selectID }}">
                            {% for option in select %}
                            {% set selected = '' %}
                            {% if option.active == option.active_state %}
                               {% set selected = 'selected' %}
                            {% endif %}
                            <option value="{{ option.Ovalue }}">{{ option.value }}</option>
                            {% endfor %}
                        </select>
                        {% endif %}
However it does not seem to work, I have a hard time knowing if your option.active is working or what it does??

**Comment by mattstein** [comment]
Are you working with a dropdown menu inside of a table? I don’t understand where `row.hasSelect`, `option.active`, `option.active_state` are coming from—those are not on the page you mentioned.

I do not understand what you’re trying to do or where the _Dropdown Fields_ page is making it less clear.

**Comment by mattstein** [comment]
Closing since I’m not sure there’s anything actionable here. If I can understand the issue I’d be happy to address it!
