### ISSUE TITLE
Set storage (and any other) to writeable on windows

### ISSUE THREAD

**Issue by flycast** [craftcms/docs#85]
New installation on local Windows 10 machine. When I try to run the initial install I get the following error:

> C:\dev/storage doesn't exist or isn't writable by PHP. Please fix that.

I have determined a list of all users on this PC and given them write access to all files in my craft installation and still the same result. On a windows install how to get Craft to see the folders as writable?

**Comment by angrybrad** [comment]
Are you using IIS for your web server?  If so, you need to assign whatever user the AppPool associated with your site is running as write permissions to the storage folder.

**Comment by flycast** [comment]
No. I am using Ampps stack. Apache.
I set every (all) users that are on that computer to be able to have full control over all files in the top level Craft foilder.

**Comment by flycast** [comment]
Ok....I am such a dumb a** sometimes! I was working on the wrong folder. I changed the folder spec in my index.html file to point to the craft installation folder and now all is well. The actual problem was my path did not exist (as the message said).

**Comment by angrybrad** [comment]
Hah... no worries, @flycast. Glad you're all sorted.
