### ISSUE TITLE
Unclear type in documentation for the backupCommand config

### ISSUE THREAD

**Issue by kbergha** [craftcms/docs#88]
### Description

The documentation for `backupCommand` states that the allowed types for this config value are: string or null.
But the last sentence in the documentation for the config states:

> This can also be set to `false` to disable database backups completely.

So is it possible to use a boolean false as well? 
If so, what would happen if you use boolean true? 

Or is supposed to be the string "false"?

### Steps to reproduce

1. Read docs at https://craftcms.com/docs/3.x/config/config-settings.html#backupcommand
2. Be confused.

### Additional info

- Craft version: 3.5.x

**Comment by mattstein** [comment]
Was able to reproduce, thank you @kbergha ;)

It [looks like](https://github.com/craftcms/cms/blob/2b5506a428bcfe384e3e43b6c9aed94206125aa1/src/db/Connection.php#L266-L278) the correct type should be `string|false|null`.

> So is it possible to use a boolean false as well?

This is the intended `false`, as it looks like any string would be treated like a command.

For example...

```php
return [
	// ...
    'backupCommand' => 'false'
	// ...
];
```

...would result in...

```
Backing up the database ... error: The shell command "false" failed with exit code 1: Command unexpectedly terminated without error message
```

> If so, what would happen if you use boolean true?

```
Backing up the database ... error: The shell command "1" failed with exit code 127: sh: 1: 1: not found
```

Submitted a PR for updating that description.
