### ISSUE TITLE
Add docs for Commerce Reset Data cli command

### ISSUE THREAD

**Issue by nfourtythree** [craftcms/docs#89]
The next release of Commerce will include the `commerce/reset-data` cli command.

This is useful for people to cleanse that DB after finishing development of a project.

https://github.com/craftcms/commerce/blob/develop/src/console/controllers/ResetDataController.php

**Comment by mattstein** [comment]
Just added a page with this, thanks for the heads up @nfourtythree! The `commerce/next` branch is ready to roll.
