### ISSUE TITLE
Macro import details in Twig 2

### ISSUE THREAD

**Issue by carlcs** [craftcms/docs#9]
This breaking change is probably worth mentioning in the Twig 2 section:

> As of Twig 2.0, macros imported in a file are not available in child templates anymore (via an `include` call for instance). You need to import macros explicitly in each file where you are using them.

http://twig.sensiolabs.org/doc/1.x/deprecated.html

**Comment by brandonkelly** [comment]
The [Macros](https://github.com/craftcms/docs/blob/master/en/changes-in-craft-3.md#macros) section has been in the upgrade since the beginning.

**Comment by carlcs** [comment]
Hm… macros is mentioned, but all that section mentiones it the one change in Twig 2 about “calling macros defined by the same template”. I don’t think Ryan’s note is redundant.

**Comment by brandonkelly** [comment]
Ah I think I misunderstood the scope of the deprecation error (I didn’t realize that Twig 1 made macros from parent templates available automatically).

Just tweaked the Macros section a bit to include both cases.
