### ISSUE TITLE
Flow of 'Element types' page

### ISSUE THREAD

**Issue by dmatthams** [craftcms/docs#91]
Firstly, this section is so much better than when I attempted this before – it pretty much reads like a tutorial and has got me setup in no time 🙌

Because this page is in a specific order, it feels a little disjointed when you get to the [Index page](https://craftcms.com/docs/3.x/extend/element-types.html#index-page) section. Once I setup the index page I expected it to show my test entries straight away, I didn't realise it required 'Table Attributes' (which is a few headings down). So it feels this should maybe be the next section after setting the up index page?

**Comment by mattstein** [comment]
Glad it’s improved and thanks for pointing this out, @dmatthams! Just reordered several of these subsections for easier reading.

**Comment by dmatthams** [comment]
Great! Another big omission is the 'new element' button, I've figured it out but can see why it's not part of this page as it probably needs more space/it's own section along with all the other CP javascript (I imagine that is on the list!).

**Comment by mattstein** [comment]
Would you mind putting each in a separate issue, @dmatthams? And “all the other CP javascript” is a bit broad—if you can narrow that or touch on the key points you’re thinking that would be helpful. Garnish.js, for example, does not have stellar documentation but it’s only one piece of the puzzle. 😅

**Comment by dmatthams** [comment]
For sure, still working my way through everything but will feed back once I'm done!
