### ISSUE TITLE
Improve “Functions”

### ISSUE THREAD

**Issue by wbrlsa** [craftcms/docs#95]
I have a suggestion for https://craftcms.com/docs/3.x/dev/functions.html

There are no examples of the code in use only descriptions of what it does.
Apparently order matters with what you are passing to this function.

One example showing the function parameters used is all that is needed.

**Comment by mattstein** [comment]
Thanks for the issue! Which function are you referring to, @wbrlsa?

**Comment by wbrlsa** [comment]
Awesome response time.. I'm surprised really.... siteUrl().
url() has a sample at the very bottom of the page, but in using siteUrl() I could use clarification.
Having issues with Craft - it keeps appending the inputted text onto the site url, rather than making it the site url.. if that makes sense.

Thank you very much

**Comment by mattstein** [comment]
> Having issues with Craft - it keeps appending the inputted text onto the site url, rather than making it the site url.. if that makes sense.

Would you mind sharing an example of this? I’m not sure I’m following. It’d be helpful to see what Twig you’re using, what you expect the output to be, and whatever output you get instead.

**Comment by wbrlsa** [comment]
My apologies, I need to go put out a fire(figurative). Can't stick around much longer but if a sample code for siteUrl() could be added it would help. Showing how to use scheme(http/https) specifically.  Thank you very much for your time!!

Have a great day and stay safe stay healthy!
