### ISSUE TITLE
Clarify using .env and .env.example files in instructions for manual installation

### ISSUE THREAD

**Issue by ryanirelan** [craftcms/docs#96]
If you copy the files in, for example, the macOS Finder then the hidden files are _not_ copied. We should clarify the instructions to note this or give instructions to route around this issue.

**Comment by ryanirelan** [comment]
After talking to Brad, I'm amending this to request that the hidden files in the manual install option are named without the leading dot and the installation instructions are updated to include a section on renaming `env`, `env-example`, and `gitignore` to `.env`, `.env-example` and `.gitignore`.

**Comment by brandonkelly** [comment]
Forgot to update this issue, but I did just make a bunch of changes to the [installation instructions](https://docs.craftcms.com/v3/installation.html), including this:

> If you’re on macOS, be careful not to lose the hidden files in there (`.env`, `.env.example`, `.gitignore`, and `web/.htaccess`).

Considering how many hidden files there are, I _think_ I’d rather just encourage people to unzip the archive directly in the place they want it to live, and keep that warning in there, then make everyone have to start adding the `.`s to the filenames.

We took the other approach with `.htaccess` in Craft 2, and that can lead to its own issues, as people miss the step about adding the `.`.
