### ISSUE TITLE
Static assets not showing when using this theme

### ISSUE THREAD

**Issue by mraza007** [craftcms/docs#97]
### Description

Hi Craft team,
I'm using this documentation theme and i really love it. Its robust and interactive.
There are few issues I'm having
When i try to host dist/ my static assets don't show up I have tried all the possibilities but no luck

Any help or insight would be greatly appreciated

**Comment by mattstein** [comment]
This is a proprietary theme we’ve developed for our own internal use only. You're welcome to use our [general-purpose theme](https://github.com/pixelandtonic/craft-docs) behind our class reference docs, however.
