### ISSUE TITLE
Improve Entry Form fields documentation

### ISSUE THREAD

**Issue by johandouma** [craftcms/docs#98]
In the docs for the Entry Form here https://craftcms.com/docs/3.x/dev/examples/entry-form.html, it is not obvious that form fields name attributes need to use the fields array like so: name="fields[customfield]". The input for the body field should have fields[body] right? 

I can see that the Guest Entries plugin README example does specify fields[body] in the field name though.

**Comment by johandouma** [comment]
Also see: https://github.com/craftcms/guest-entries/issues/61

**Comment by mattstein** [comment]
Correct and good catch @johandouma, thanks! This example has a new home in the knowledge base, which I’ve updated to fix the error you pointed out: https://craftcms.com/knowledge-base/entry-form
