### ISSUE TITLE
Entry Form broken with "Show the Title field" unticked

### ISSUE THREAD

**Issue by johandouma** [craftcms/docs#99]
### Description

The Entry Form submission doesn't work when "Show the Title field" is unticked for the entry type that is being submitted. The error I got suggested that the slug cannot be empty. The work around was to reeanble the Show the Title field and pass it a title. 

This was in Craft version: 3.4.30

**Comment by mattstein** [comment]
@johandouma This is intended behavior: the slug must not be empty, so the error is correct, and a provided title will automatically be used to *generate* a slug if one isn’t explicitly provided. (Same as how it works in the control panel.)
